//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'organizationElementItemEditController';
    angular.module('main')
        .controller(controllerId, ['organizationElementItemService',
            'elementItemService',
            'organizationService',
            'logger',
            '$location',
            '$routeParams',
            organizationElementItemEditController]);

    function organizationElementItemEditController(organizationElementItemService,
		elementItemService,
		organizationService,
		logger,
		$location,
		$routeParams) {
        logger = logger.forSource(controllerId);

        var isNew = $location.path() === '/manage/organizationElementItem/new';
        var isSaving = false;

        // Controller methods (alphabetically)
        var vm = this;
        vm.elementItemSet = [];
        vm.organizationSet = [];
        vm.cancelChanges = cancelChanges;
        vm.isSaveDisabled = isSaveDisabled;
        vm.organizationElementItem = null;
        vm.saveChanges = saveChanges;
        vm.hasChanges = hasChanges;

        initialize();

        /*** Implementations ***/

        function cancelChanges() {

            $location.path('/manage/organizationElementItem');

            if (organizationElementItemService.hasChanges()) {
                organizationElementItemService.rejectChanges();
                logWarning('Discarded pending change(s)', null, true);
            }
        }

        function hasChanges() {
            return organizationElementItemService.hasChanges();
        }

        function initialize() {

            elementItemService.getElementItemSet(false)
                .then(function (data) {
                    vm.elementItemSet = data;
                });

            organizationService.getOrganizationSet(false)
                .then(function (data) {
                    vm.organizationSet = data;
                });

            if (isNew) {
                // TODO For development enviroment, create test entity?
            }
            else {
                organizationElementItemService.getOrganizationElementItem($routeParams.Id)
                    .then(function (data) {
                        vm.organizationElementItem = data;
                    })
                    .catch(function (error) {
                        // TODO User-friendly message?
                    });
            }
        };

        function isSaveDisabled() {
            return isSaving ||
                (!isNew && !organizationElementItemService.hasChanges());
        }

        function saveChanges() {

            if (isNew) {
                organizationElementItemService.createOrganizationElementItem(vm.organizationElementItem);
            } else {
                // To be able to do concurrency check, RowVersion field needs to be send to server
				// Since breeze only sends the modified fields, a fake modification had to be applied to RowVersion field
                var rowVersion = vm.organizationElementItem.RowVersion;
                vm.organizationElementItem.RowVersion = '';
                vm.organizationElementItem.RowVersion = rowVersion;
            }

            isSaving = true;
            organizationElementItemService.saveChanges()
                .then(function (result) {
                    $location.path('/manage/organizationElementItem');
                })
                .catch(function (error) {
                    // Conflict (Concurrency exception)
                    if (error.status === '409') {
                        // TODO Try to recover!
                    }
                })
                .finally(function () {
                    isSaving = false;
                });
        }
    };
})();
