//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userResourcePoolIndexValueEditController';
    angular.module('main')
        .controller(controllerId, ['userResourcePoolIndexValueService',
            'organizationService',
            'userResourcePoolIndexService',
            'logger',
            '$location',
            '$routeParams',
            userResourcePoolIndexValueEditController]);

    function userResourcePoolIndexValueEditController(userResourcePoolIndexValueService,
		organizationService,
		userResourcePoolIndexService,
		logger,
		$location,
		$routeParams) {
        logger = logger.forSource(controllerId);

        var isNew = $location.path() === '/manage/userResourcePoolIndexValue/new';
        var isSaving = false;

        // Controller methods (alphabetically)
        var vm = this;
        vm.organizationSet = [];
        vm.userResourcePoolIndexSet = [];
        vm.cancelChanges = cancelChanges;
        vm.isSaveDisabled = isSaveDisabled;
        vm.userResourcePoolIndexValue = null;
        vm.saveChanges = saveChanges;
        vm.hasChanges = hasChanges;

        initialize();

        /*** Implementations ***/

        function cancelChanges() {

            $location.path('/manage/userResourcePoolIndexValue');

            if (userResourcePoolIndexValueService.hasChanges()) {
                userResourcePoolIndexValueService.rejectChanges();
                logWarning('Discarded pending change(s)', null, true);
            }
        }

        function hasChanges() {
            return userResourcePoolIndexValueService.hasChanges();
        }

        function initialize() {

            organizationService.getOrganizationSet(false)
                .then(function (data) {
                    vm.organizationSet = data;
                });

            userResourcePoolIndexService.getUserResourcePoolIndexSet(false)
                .then(function (data) {
                    vm.userResourcePoolIndexSet = data;
                });

            if (isNew) {
                // TODO For development enviroment, create test entity?
            }
            else {
                userResourcePoolIndexValueService.getUserResourcePoolIndexValue($routeParams.Id)
                    .then(function (data) {
                        vm.userResourcePoolIndexValue = data;
                    })
                    .catch(function (error) {
                        // TODO User-friendly message?
                    });
            }
        };

        function isSaveDisabled() {
            return isSaving ||
                (!isNew && !userResourcePoolIndexValueService.hasChanges());
        }

        function saveChanges() {

            if (isNew) {
                userResourcePoolIndexValueService.createUserResourcePoolIndexValue(vm.userResourcePoolIndexValue);
            } else {
                // To be able to do concurrency check, RowVersion field needs to be send to server
				// Since breeze only sends the modified fields, a fake modification had to be applied to RowVersion field
                var rowVersion = vm.userResourcePoolIndexValue.RowVersion;
                vm.userResourcePoolIndexValue.RowVersion = '';
                vm.userResourcePoolIndexValue.RowVersion = rowVersion;
            }

            isSaving = true;
            userResourcePoolIndexValueService.saveChanges()
                .then(function (result) {
                    $location.path('/manage/userResourcePoolIndexValue');
                })
                .catch(function (error) {
                    // Conflict (Concurrency exception)
                    if (error.status === '409') {
                        // TODO Try to recover!
                    }
                })
                .finally(function () {
                    isSaving = false;
                });
        }
    };
})();
