//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects
{
    using System;
    using System.ComponentModel.DataAnnotations;
    
    public class OrganizationMetadata
    {
        [Display(Name = "Id")]
        public int Id { get; set; }
    
        [Display(Name = "SectorId")]
        public byte SectorId { get; set; }
    
        [Display(Name = "Organization")]
        public string Name { get; set; }
    
        [Display(Name = "Production Cost")]
        public decimal ProductionCost { get; set; }
    
        [Display(Name = "Sales Price")]
        public decimal SalesPrice { get; set; }
    
        [Display(Name = "LicenseId")]
        public short LicenseId { get; set; }
    
        [Display(Name = "Number of Sales")]
        public int NumberOfSales { get; set; }
    
        [Display(Name = "CreatedOn")]
        public System.DateTime CreatedOn { get; set; }
    
        [Display(Name = "ModifiedOn")]
        public System.DateTime ModifiedOn { get; set; }
    
        [Display(Name = "DeletedOn")]
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
    }
}
