//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'licenseListController';
    angular.module('main')
        .controller(controllerId, ['licenseService', 'logger', licenseListController]);

    function licenseListController(licenseService, logger) {

        logger = logger.forSource(controllerId);
        var logError = logger.logError;
        var logSuccess = logger.logSuccess;

        var vm = this;
        vm.deleteLicense = deleteLicense;
        vm.licenseSet = [];

        initialize();

        function initialize() {
            getLicenseSet();
        };

        function deleteLicense(license) {
            licenseService.deleteLicense(license);

            licenseService.saveChanges()
                .then(function () {
                    vm.licenseSet.splice(vm.licenseSet.indexOf(license), 1);
                    logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getLicenseSet(forceRefresh) {
            return licenseService.getLicenseSet(forceRefresh).then(function (data) {
                return vm.licenseSet = data;
            });
        }
    };
})();
