//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'resourcePoolListController';
    angular.module('main')
        .controller(controllerId, ['resourcePoolService', 'logger', resourcePoolListController]);

    function resourcePoolListController(resourcePoolService, logger) {

        logger = logger.forSource(controllerId);
        var logError = logger.logError;
        var logSuccess = logger.logSuccess;

        var vm = this;
        vm.deleteResourcePool = deleteResourcePool;
        vm.resourcePoolSet = [];

        initialize();

        function initialize() {
            getResourcePoolSet();
        };

        function deleteResourcePool(resourcePool) {
            resourcePoolService.deleteResourcePool(resourcePool);

            resourcePoolService.saveChanges()
                .then(function () {
                    vm.resourcePoolSet.splice(vm.resourcePoolSet.indexOf(resourcePool), 1);
                    logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getResourcePoolSet() {
            return resourcePoolService.getResourcePoolSet().then(function (data) {
                return vm.resourcePoolSet = data;
            });
        }
    };
})();
