//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'resourcepoolorganizationListController';
    angular.module('main')
        .controller(controllerId, ['resourcepoolorganizationService', 'logger', resourcepoolorganizationListController]);

    function resourcepoolorganizationListController(resourcepoolorganizationService, logger) {

        logger = logger.forSource(controllerId);
        var logError = logger.logError;
        var logSuccess = logger.logSuccess;

        var vm = this;
        vm.deleteResourcePoolOrganization = deleteResourcePoolOrganization;
        vm.resourcepoolorganizationSet = [];

        initialize();

        function initialize() {
            getResourcePoolOrganizationSet();
        };

        function deleteResourcePoolOrganization(resourcepoolorganization) {
            resourcepoolorganizationService.deleteResourcePoolOrganization(resourcepoolorganization);

            resourcepoolorganizationService.saveChanges()
                .then(function () {
                    vm.resourcepoolorganizationSet.splice(vm.resourcepoolorganizationSet.indexOf(resourcepoolorganization), 1);
                    logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getResourcePoolOrganizationSet(forceRefresh) {
            return resourcepoolorganizationService.getResourcePoolOrganizationSet(forceRefresh).then(function (data) {
                return vm.resourcepoolorganizationSet = data;
            });
        }
    };
})();
