//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'resourcePoolIndexListController';
    angular.module('main')
        .controller(controllerId, ['resourcePoolIndexService',
            'logger',
			resourcePoolIndexListController]);

    function resourcePoolIndexListController(resourcePoolIndexService,
        logger) {
        logger = logger.forSource(controllerId);

        var vm = this;
        vm.deleteResourcePoolIndex = deleteResourcePoolIndex;
        vm.resourcePoolIndexSet = [];

        initialize();

        function initialize() {
            getResourcePoolIndexSet();
        };

        function deleteResourcePoolIndex(resourcePoolIndex) {
            resourcePoolIndexService.deleteResourcePoolIndex(resourcePoolIndex);

            resourcePoolIndexService.saveChanges()
                .then(function () {
                    vm.resourcePoolIndexSet.splice(vm.resourcePoolIndexSet.indexOf(resourcePoolIndex), 1);
                    logger.logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logger.logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getResourcePoolIndexSet() {
            resourcePoolIndexService.getResourcePoolIndexSet(false)
			    .then(function (data) {
                    vm.resourcePoolIndexSet = data;
                });
        }
    };
})();
