//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'sectorEditController';
    angular.module('main')
        .controller(controllerId, ['sectorService',
            'resourcePoolService',
            'logger',
            '$location',
            '$routeParams',
            sectorEditController]);

    function sectorEditController(sectorService,
		resourcePoolService,
		logger,
		$location,
		$routeParams) {
        logger = logger.forSource(controllerId);

        var isNew = $location.path() === '/Sector/new';
        var isSaving = false;

        // Controller methods (alphabetically)
        var vm = this;
        vm.resourcePoolSet = [];
        vm.cancelChanges = cancelChanges;
        vm.isSaveDisabled = isSaveDisabled;
        vm.sector = null;
        vm.saveChanges = saveChanges;
        vm.hasChanges = hasChanges;

        initialize();

        /*** Implementations ***/

        function cancelChanges() {

            $location.path('/Sector');

            if (sectorService.hasChanges()) {
                sectorService.rejectChanges();
                logWarning('Discarded pending change(s)', null, true);
            }
        }

        function hasChanges() {
            return sectorService.hasChanges();
        }

        function initialize() {

            resourcePoolService.getResourcePoolSet(false)
                .then(function (data) {
                    vm.resourcePoolSet = data;
                });

            if (isNew) {
                // TODO For development enviroment, create test entity?
            }
            else {
                sectorService.getSector($routeParams.Id)
                    .then(function (data) {
                        vm.sector = data;
                    })
                    .catch(function (error) {
                        // TODO User-friendly message?
                    });
            }
        };

        function isSaveDisabled() {
            return isSaving ||
                (!isNew && !sectorService.hasChanges());
        }

        function saveChanges() {

            if (isNew) {
                sectorService.createSector(vm.sector);
            } else {
                // To be able to do concurrency check, RowVersion field needs to be send to server
				// Since breeze only sends the modified fields, a fake modification had to be applied to RowVersion field
                var rowVersion = vm.sector.RowVersion;
                vm.sector.RowVersion = '';
                vm.sector.RowVersion = rowVersion;
            }

            isSaving = true;
            sectorService.saveChanges()
                .then(function (result) {
                    $location.path('/Sector');
                })
                .catch(function (error) {
                    // Conflict (Concurrency exception)
                    if (error.status === '409') {
                        // TODO Try to recover!
                    }
                })
                .finally(function () {
                    isSaving = false;
                });
        }
    };
})();
