//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userOrganizationEditController';
    angular.module('main')
        .controller(controllerId, ['userOrganizationService',
            'organizationService',
            'userService',
            'logger',
            '$location',
            '$routeParams',
            userOrganizationEditController]);

    function userOrganizationEditController(userOrganizationService,
		organizationService,
		userService,
		logger,
		$location,
		$routeParams) {
        logger = logger.forSource(controllerId);

        var isNew = $location.path() === '/UserOrganization/new';
        var isSaving = false;

        // Controller methods (alphabetically)
        var vm = this;
        vm.organizationSet = [];
        vm.userSet = [];
        vm.cancelChanges = cancelChanges;
        vm.isSaveDisabled = isSaveDisabled;
        vm.userOrganization = null;
        vm.saveChanges = saveChanges;
        vm.hasChanges = hasChanges;

        initialize();

        /*** Implementations ***/

        function cancelChanges() {

            $location.path('/UserOrganization');

            if (userOrganizationService.hasChanges()) {
                userOrganizationService.rejectChanges();
                logWarning('Discarded pending change(s)', null, true);
            }
        }

        function hasChanges() {
            return userOrganizationService.hasChanges();
        }

        function initialize() {

            organizationService.getOrganizationSet(false)
                .then(function (data) {
                    vm.organizationSet = data;
                });

            userService.getUserSet(false)
                .then(function (data) {
                    vm.userSet = data;
                });

            if (isNew) {
                // TODO For development enviroment, create test entity?
            }
            else {
                userOrganizationService.getUserOrganization($routeParams.Id)
                    .then(function (data) {
                        vm.userOrganization = data;
                    })
                    .catch(function (error) {
                        // TODO User-friendly message?
                    });
            }
        };

        function isSaveDisabled() {
            return isSaving ||
                (!isNew && !userOrganizationService.hasChanges());
        }

        function saveChanges() {

            if (isNew) {
                userOrganizationService.createUserOrganization(vm.userOrganization);
            } else {
                // To be able to do concurrency check, RowVersion field needs to be send to server
				// Since breeze only sends the modified fields, a fake modification had to be applied to RowVersion field
                var rowVersion = vm.userOrganization.RowVersion;
                vm.userOrganization.RowVersion = '';
                vm.userOrganization.RowVersion = rowVersion;
            }

            isSaving = true;
            return userOrganizationService.saveChanges()
                .then(function (result) {
                    $location.path('/UserOrganization');
                })
                .catch(function (error) {
                    // Conflict (Concurrency exception)
                    if (error.status === '409') {
                        // TODO Try to recover!
                    }
                })
                .finally(function () {
                    isSaving = false;
                });
        }
    };
})();
