//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userOrganizationEditController';
    angular.module('main')
        .controller(controllerId, ['userOrganizationService',
            'organizationService',
            'userService',
            'logger',
            '$location',
            '$routeParams',
            userOrganizationEditController]);

    function userOrganizationEditController(userOrganizationService,
		organizationService,
		userService,
		logger,
		$location,
		$routeParams) {
        logger = logger.forSource(controllerId);

        var isNew = $location.path() === '/UserOrganization/new';
        var isSaving = false;

        // Controller methods (alphabetically)
        var vm = this;
        vm.organizationSet = [];
        vm.userSet = [];
        vm.cancelChanges = cancelChanges;
        vm.isSaveDisabled = isSaveDisabled;
        vm.userOrganization = null;
        vm.saveChanges = saveChanges;
        vm.hasChanges = hasChanges;

        initialize();

        /*** Implementations ***/

        function cancelChanges() {

            $location.path('/UserOrganization/');

            if (userOrganizationService.hasChanges()) {
                userOrganizationService.rejectChanges();
                logWarning('Discarded pending change(s)', null, true);
            }
        }

        function hasChanges() {
            return userOrganizationService.hasChanges();
        }

        function initialize() {

            organizationService.getOrganizationSet(false)
                .then(function (data) {
                    vm.organizationSet = data;
                });

            // TODO Catch?

            userService.getUserSet(false)
                .then(function (data) {
                    vm.userSet = data;
                });

            // TODO Catch?

            if (isNew) {
                // TODO Only for development, create test entity ?!
            }
            else {
                userOrganizationService.getUserOrganization($routeParams.Id)
                    .then(function (data) {
                        vm.userOrganization = data;
                    })
                    .catch(function (error) {
                        logger.logError("Boooo, we failed: " + error.message, null, true);
                        // Todo: more sophisticated recovery. 
                        // Here we just blew it all away and start over
                        // refresh();
                    });
            }
        };

        function isSaveDisabled() {
            return isSaving ||
                (!isNew && !userOrganizationService.hasChanges());
        }

        function saveChanges() {

            if (isNew) {
                userOrganizationService.createUserOrganization(vm.userOrganization);
            }

            isSaving = true;
            return userOrganizationService.saveChanges()
                .then(function () {
                    logger.logSuccess("Hooray we saved", null, true);
                    $location.path('/UserOrganization/');
                })
                .catch(function (error) {
                    logger.logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
                .finally(function () {
                    isSaving = false;
                });
        }
    };
})();
