//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userresourcepoolorganizationListController';
    angular.module('main')
        .controller(controllerId, ['userresourcepoolorganizationService', 'logger', userresourcepoolorganizationListController]);

    function userresourcepoolorganizationListController(userresourcepoolorganizationService, logger) {

        logger = logger.forSource(controllerId);
        var logError = logger.logError;
        var logSuccess = logger.logSuccess;

        var vm = this;
        vm.deleteUserResourcePoolOrganization = deleteUserResourcePoolOrganization;
        vm.userresourcepoolorganizationSet = [];

        initialize();

        function initialize() {
            getUserResourcePoolOrganizationSet();
        };

        function deleteUserResourcePoolOrganization(userresourcepoolorganization) {
            userresourcepoolorganizationService.deleteUserResourcePoolOrganization(userresourcepoolorganization);

            userresourcepoolorganizationService.saveChanges()
                .then(function () {
                    vm.userresourcepoolorganizationSet.splice(vm.userresourcepoolorganizationSet.indexOf(userresourcepoolorganization), 1);
                    logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getUserResourcePoolOrganizationSet(forceRefresh) {
            return userresourcepoolorganizationService.getUserResourcePoolOrganizationSet(forceRefresh).then(function (data) {
                return vm.userresourcepoolorganizationSet = data;
            });
        }
    };
})();
