//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userOrganizationListController';
    angular.module('main')
        .controller(controllerId, ['userOrganizationService',
            'userService',
            'logger',
			userOrganizationListController]);

    function userOrganizationListController(userOrganizationService,
        userService,
        logger) {
        logger = logger.forSource(controllerId);

        var vm = this;
        vm.deleteUserOrganization = deleteUserOrganization;
        vm.userOrganizationSet = [];

        initialize();

        function initialize() {
            getUserOrganizationSet();
        };

        function deleteUserOrganization(userOrganization) {
            userOrganizationService.deleteUserOrganization(userOrganization);

            userOrganizationService.saveChanges()
                .then(function () {
                    vm.userOrganizationSet.splice(vm.userOrganizationSet.indexOf(userOrganization), 1);
                    logger.logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logger.logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getUserOrganizationSet() {
            userService.getCurrentUser()
			    .success(function (currentUser) {
					userOrganizationService.getUserOrganizationSet(currentUser.Id, false)
						.then(function (data) {
							vm.userOrganizationSet = data;
						});
			    });
        }
    };
})();
