//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userLicenseRatingEditController';
    angular.module('main')
        .controller(controllerId, ['userLicenseRatingService',
            'licenseService',
            'userService',
            'logger',
            '$location',
            '$routeParams',
            userLicenseRatingEditController]);

    function userLicenseRatingEditController(userLicenseRatingService,
		licenseService,
		userService,
		logger,
		$location,
		$routeParams) {
        logger = logger.forSource(controllerId);

        var isNew = $location.path() === '/UserLicenseRating/new';
        var isSaving = false;

        // Controller methods (alphabetically)
        var vm = this;
        vm.licenseSet = [];
        vm.userSet = [];
        vm.cancelChanges = cancelChanges;
        vm.isSaveDisabled = isSaveDisabled;
        vm.userLicenseRating = null;
        vm.saveChanges = saveChanges;
        vm.hasChanges = hasChanges;

        initialize();

        /*** Implementations ***/

        function cancelChanges() {

            $location.path('/UserLicenseRating');

            if (userLicenseRatingService.hasChanges()) {
                userLicenseRatingService.rejectChanges();
                logWarning('Discarded pending change(s)', null, true);
            }
        }

        function hasChanges() {
            return userLicenseRatingService.hasChanges();
        }

        function initialize() {

            licenseService.getLicenseSet(false)
                .then(function (data) {
                    vm.licenseSet = data;
                });

            userService.getUserSet(false)
                .then(function (data) {
                    vm.userSet = data;
                });

            if (isNew) {
                // TODO For development enviroment, create test entity?
            }
            else {
                userLicenseRatingService.getUserLicenseRating($routeParams.Id)
                    .then(function (data) {
                        vm.userLicenseRating = data;
                    })
                    .catch(function (error) {
                        // TODO User-friendly message?
                    });
            }
        };

        function isSaveDisabled() {
            return isSaving ||
                (!isNew && !userLicenseRatingService.hasChanges());
        }

        function saveChanges() {

            if (isNew) {
                userLicenseRatingService.createUserLicenseRating(vm.userLicenseRating);
            } else {
                // To be able to do concurrency check, RowVersion field needs to be send to server
				// Since breeze only sends the modified fields, a fake modification had to be applied to RowVersion field
                var rowVersion = vm.userLicenseRating.RowVersion;
                vm.userLicenseRating.RowVersion = '';
                vm.userLicenseRating.RowVersion = rowVersion;
            }

            isSaving = true;
            userLicenseRatingService.saveChanges()
                .then(function (result) {
                    $location.path('/UserLicenseRating');
                })
                .catch(function (error) {
                    // Conflict (Concurrency exception)
                    if (error.status === '409') {
                        // TODO Try to recover!
                    }
                })
                .finally(function () {
                    isSaving = false;
                });
        }
    };
})();
