//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userResourcePoolOrganizationListController';
    angular.module('main')
        .controller(controllerId, ['userResourcePoolOrganizationService',
            'userService',
            'logger',
			userResourcePoolOrganizationListController]);

    function userResourcePoolOrganizationListController(userResourcePoolOrganizationService,
        userService,
        logger) {

        logger = logger.forSource(controllerId);
        var logError = logger.logError;
        var logSuccess = logger.logSuccess;

        var vm = this;
        vm.deleteUserResourcePoolOrganization = deleteUserResourcePoolOrganization;
        vm.userResourcePoolOrganizationSet = [];

        initialize();

        function initialize() {
            getUserResourcePoolOrganizationSet();
        };

        function deleteUserResourcePoolOrganization(userResourcePoolOrganization) {
            userResourcePoolOrganizationService.deleteUserResourcePoolOrganization(userResourcePoolOrganization);

            userResourcePoolOrganizationService.saveChanges()
                .then(function () {
                    vm.userResourcePoolOrganizationSet.splice(vm.userResourcePoolOrganizationSet.indexOf(userResourcePoolOrganization), 1);
                    logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getUserResourcePoolOrganizationSet() {
            userService.getCurrentUser()
			    .success(function (currentUser) {
					userResourcePoolOrganizationService.getUserResourcePoolOrganizationSet(currentUser.Id, false)
						.then(function (data) {
							vm.userResourcePoolOrganizationSet = data;
						});
			    });
        }
    };
})();
