//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userLicenseRatingEditController';
    angular.module('main')
        .controller(controllerId, ['userLicenseRatingService',
            'licenseService',
            'userService',
            'logger',
            '$location',
            '$routeParams',
            userLicenseRatingEditController]);

    function userLicenseRatingEditController(userLicenseRatingService,
		licenseService,
		userService,
		logger,
		$location,
		$routeParams) {

        logger = logger.forSource(controllerId);
        var logError = logger.logError;
        var logSuccess = logger.logSuccess;

        var isNew = $location.path() === '/UserLicenseRating/new';
        var isSaving = false;

        // Controller methods (alphabetically)
        var vm = this;
        vm.licenseSet = [];
        vm.userSet = [];
        vm.cancelChanges = cancelChanges;
        vm.isSaveDisabled = isSaveDisabled;
        vm.userLicenseRating = null;
        vm.saveChanges = saveChanges;
        vm.hasChanges = hasChanges;

        initialize();

        /*** Implementations ***/

        function cancelChanges() {

            $location.path('/UserLicenseRating/');

            if (userLicenseRatingService.hasChanges()) {
                userLicenseRatingService.rejectChanges();
                logWarning('Discarded pending change(s)', null, true);
            }
        }

        function hasChanges() {
            return userLicenseRatingService.hasChanges();
        }

        function initialize() {

            licenseService.getLicenseSet()
                .then(function (data) {
                    vm.licenseSet = data;
                });

            // TODO Catch?

            userService.getUserSet()
                .then(function (data) {
                    vm.userSet = data;
                });

            // TODO Catch?

            if (isNew) {
                // TODO Only for development, create test entity ?!
            }
            else {
                userLicenseRatingService.getUserLicenseRating($routeParams.Id)
                    .then(function (data) {
                        vm.userLicenseRating = data;
                    })
                    .catch(function (error) {
                        logError("Boooo, we failed: " + error.message, null, true);
                        // Todo: more sophisticated recovery. 
                        // Here we just blew it all away and start over
                        // refresh();
                    });
            }
        };

        function isSaveDisabled() {
            return isSaving ||
                (!isNew && !userLicenseRatingService.hasChanges());
        }

        function saveChanges() {

            if (isNew) {
                userLicenseRatingService.createUserLicenseRating(vm.userLicenseRating);
            }

            isSaving = true;
            return userLicenseRatingService.saveChanges()
                .then(function () {
                    logSuccess("Hooray we saved", null, true);
                    $location.path('/UserLicenseRating/');
                })
                .catch(function (error) {
                    logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
                .finally(function () {
                    isSaving = false;
                });
        }
    };
})();
