//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userResourcePoolEditController';
    angular.module('main')
        .controller(controllerId, ['userResourcePoolService',
            'userService',
            'resourcePoolService',
            'logger',
            '$location',
            '$routeParams',
            userResourcePoolEditController]);

    function userResourcePoolEditController(userResourcePoolService,
		userService,
		resourcePoolService,
		logger,
		$location,
		$routeParams) {

        logger = logger.forSource(controllerId);
        var logError = logger.logError;
        var logSuccess = logger.logSuccess;

        var isNew = $location.path() === '/UserResourcePool/new';
        var isSaving = false;

        // Controller methods (alphabetically)
        var vm = this;
        vm.userSet = [];
        vm.resourcePoolSet = [];
        vm.cancelChanges = cancelChanges;
        vm.isSaveDisabled = isSaveDisabled;
        vm.userResourcePool = null;
        vm.saveChanges = saveChanges;
        vm.hasChanges = hasChanges;

        initialize();

        /*** Implementations ***/

        function cancelChanges() {

            $location.path('/UserResourcePool/');

            if (userResourcePoolService.hasChanges()) {
                userResourcePoolService.rejectChanges();
                logWarning('Discarded pending change(s)', null, true);
            }
        }

        function hasChanges() {
            return userResourcePoolService.hasChanges();
        }

        function initialize() {

            userService.getUserSet()
                .then(function (data) {
                    vm.userSet = data;
                });

            // TODO Catch?

            resourcePoolService.getResourcePoolSet()
                .then(function (data) {
                    vm.resourcePoolSet = data;
                });

            // TODO Catch?

            if (isNew) {
                // TODO Only for development, create test entity ?!
            }
            else {
                userResourcePoolService.getUserResourcePool($routeParams.Id)
                    .then(function (data) {
                        vm.userResourcePool = data;
                    })
                    .catch(function (error) {
                        logError("Boooo, we failed: " + error.message, null, true);
                        // Todo: more sophisticated recovery. 
                        // Here we just blew it all away and start over
                        // refresh();
                    });
            }
        };

        function isSaveDisabled() {
            return isSaving ||
                (!isNew && !userResourcePoolService.hasChanges());
        }

        function saveChanges() {

            if (isNew) {
                userResourcePoolService.createUserResourcePool(vm.userResourcePool);
            }

            isSaving = true;
            return userResourcePoolService.saveChanges()
                .then(function () {
                    logSuccess("Hooray we saved", null, true);
                    $location.path('/UserResourcePool/');
                })
                .catch(function (error) {
                    logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
                .finally(function () {
                    isSaving = false;
                });
        }
    };
})();
