//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userResourcePoolOrganizationEditController';
    angular.module('main')
        .controller(controllerId, ['userResourcePoolOrganizationService',
            'userService',
            'resourcePoolOrganizationService',
            'logger',
            '$location',
            '$routeParams',
            userResourcePoolOrganizationEditController]);

    function userResourcePoolOrganizationEditController(userResourcePoolOrganizationService,
		userService,
		resourcePoolOrganizationService,
		logger,
		$location,
		$routeParams) {
        logger = logger.forSource(controllerId);

        var isNew = $location.path() === '/UserResourcePoolOrganization/new';
        var isSaving = false;

        // Controller methods (alphabetically)
        var vm = this;
        vm.userSet = [];
        vm.resourcePoolOrganizationSet = [];
        vm.cancelChanges = cancelChanges;
        vm.isSaveDisabled = isSaveDisabled;
        vm.userResourcePoolOrganization = null;
        vm.saveChanges = saveChanges;
        vm.hasChanges = hasChanges;

        initialize();

        /*** Implementations ***/

        function cancelChanges() {

            $location.path('/UserResourcePoolOrganization/');

            if (userResourcePoolOrganizationService.hasChanges()) {
                userResourcePoolOrganizationService.rejectChanges();
                logWarning('Discarded pending change(s)', null, true);
            }
        }

        function hasChanges() {
            return userResourcePoolOrganizationService.hasChanges();
        }

        function initialize() {

            userService.getUserSet(false)
                .then(function (data) {
                    vm.userSet = data;
                });

            // TODO Catch?

            resourcePoolOrganizationService.getResourcePoolOrganizationSet(false)
                .then(function (data) {
                    vm.resourcePoolOrganizationSet = data;
                });

            // TODO Catch?

            if (isNew) {
                // TODO Only for development, create test entity ?!
            }
            else {
                userResourcePoolOrganizationService.getUserResourcePoolOrganization($routeParams.Id)
                    .then(function (data) {
                        vm.userResourcePoolOrganization = data;
                    })
                    .catch(function (error) {
                        logger.logError("Boooo, we failed: " + error.message, null, true);
                        // Todo: more sophisticated recovery. 
                        // Here we just blew it all away and start over
                        // refresh();
                    });
            }
        };

        function isSaveDisabled() {
            return isSaving ||
                (!isNew && !userResourcePoolOrganizationService.hasChanges());
        }

        function saveChanges() {

            if (isNew) {
                userResourcePoolOrganizationService.createUserResourcePoolOrganization(vm.userResourcePoolOrganization);
            }

            isSaving = true;
            return userResourcePoolOrganizationService.saveChanges()
                .then(function () {
                    logger.logSuccess("Hooray we saved", null, true);
                    $location.path('/UserResourcePoolOrganization/');
                })
                .catch(function (error) {
                    logger.logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
                .finally(function () {
                    isSaving = false;
                });
        }
    };
})();
