//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userresourcepoolListController';
    angular.module('main')
        .controller(controllerId, ['userresourcepoolService', 'logger', userresourcepoolListController]);

    function userresourcepoolListController(userresourcepoolService, logger) {

        logger = logger.forSource(controllerId);
        var logError = logger.logError;
        var logSuccess = logger.logSuccess;

        var vm = this;
        vm.deleteUserResourcePool = deleteUserResourcePool;
        vm.userresourcepoolSet = [];

        initialize();

        function initialize() {
            getUserResourcePoolSet();
        };

        function deleteUserResourcePool(userresourcepool) {
            userresourcepoolService.deleteUserResourcePool(userresourcepool);

            userresourcepoolService.saveChanges()
                .then(function () {
                    vm.userresourcepoolSet.splice(vm.userresourcepoolSet.indexOf(userresourcepool), 1);
                    logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getUserResourcePoolSet(forceRefresh) {
            return userresourcepoolService.getUserResourcePoolSet(forceRefresh).then(function (data) {
                return vm.userresourcepoolSet = data;
            });
        }
    };
})();
