//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'usersectorratingListController';
    angular.module('main')
        .controller(controllerId, ['usersectorratingService', 'logger', usersectorratingListController]);

    function usersectorratingListController(usersectorratingService, logger) {

        logger = logger.forSource(controllerId);
        var logError = logger.logError;
        var logSuccess = logger.logSuccess;

        var vm = this;
        vm.deleteUserSectorRating = deleteUserSectorRating;
        vm.usersectorratingSet = [];

        initialize();

        function initialize() {
            getUserSectorRatingSet();
        };

        function deleteUserSectorRating(usersectorrating) {
            usersectorratingService.deleteUserSectorRating(usersectorrating);

            usersectorratingService.saveChanges()
                .then(function () {
                    vm.usersectorratingSet.splice(vm.usersectorratingSet.indexOf(usersectorrating), 1);
                    logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getUserSectorRatingSet(forceRefresh) {
            return usersectorratingService.getUserSectorRatingSet(forceRefresh).then(function (data) {
                return vm.usersectorratingSet = data;
            });
        }
    };
})();
