//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userLicenseRatingListController';
    angular.module('main')
        .controller(controllerId, ['userLicenseRatingService', 'logger', userLicenseRatingListController]);

    function userLicenseRatingListController(userLicenseRatingService, logger) {

        logger = logger.forSource(controllerId);
        var logError = logger.logError;
        var logSuccess = logger.logSuccess;

        var vm = this;
        vm.deleteUserLicenseRating = deleteUserLicenseRating;
        vm.userLicenseRatingSet = [];

        initialize();

        function initialize() {
            getUserLicenseRatingSet();
        };

        function deleteUserLicenseRating(userLicenseRating) {
            userLicenseRatingService.deleteUserLicenseRating(userLicenseRating);

            userLicenseRatingService.saveChanges()
                .then(function () {
                    vm.userLicenseRatingSet.splice(vm.userLicenseRatingSet.indexOf(userLicenseRating), 1);
                    logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getUserLicenseRatingSet() {
            userLicenseRatingService.getUserLicenseRatingSet().then(function (data) {
                vm.userLicenseRatingSet = data;
            });
        }
    };
})();
