//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userlicenseratingListController';
    angular.module('main')
        .controller(controllerId, ['userlicenseratingService', 'logger', userlicenseratingListController]);

    function userlicenseratingListController(userlicenseratingService, logger) {

        logger = logger.forSource(controllerId);
        var logError = logger.logError;
        var logSuccess = logger.logSuccess;

        var vm = this;
        vm.deleteUserLicenseRating = deleteUserLicenseRating;
        vm.userlicenseratingSet = [];

        initialize();

        function initialize() {
            getUserLicenseRatingSet();
        };

        function deleteUserLicenseRating(userlicenserating) {
            userlicenseratingService.deleteUserLicenseRating(userlicenserating);

            userlicenseratingService.saveChanges()
                .then(function () {
                    vm.userlicenseratingSet.splice(vm.userlicenseratingSet.indexOf(userlicenserating), 1);
                    logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getUserLicenseRatingSet(forceRefresh) {
            return userlicenseratingService.getUserLicenseRatingSet(forceRefresh).then(function (data) {
                return vm.userlicenseratingSet = data;
            });
        }
    };
})();
