//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userSectorRatingEditController';
    angular.module('main')
        .controller(controllerId, ['userSectorRatingService',
            'sectorService',
            'userService',
            'logger',
            '$location',
            '$routeParams',
            userSectorRatingEditController]);

    function userSectorRatingEditController(userSectorRatingService,
		sectorService,
		userService,
		logger,
		$location,
		$routeParams) {
        logger = logger.forSource(controllerId);

        var isNew = $location.path() === '/UserSectorRating/new';
        var isSaving = false;

        // Controller methods (alphabetically)
        var vm = this;
        vm.sectorSet = [];
        vm.userSet = [];
        vm.cancelChanges = cancelChanges;
        vm.isSaveDisabled = isSaveDisabled;
        vm.userSectorRating = null;
        vm.saveChanges = saveChanges;
        vm.hasChanges = hasChanges;

        initialize();

        /*** Implementations ***/

        function cancelChanges() {

            $location.path('/UserSectorRating');

            if (userSectorRatingService.hasChanges()) {
                userSectorRatingService.rejectChanges();
                logWarning('Discarded pending change(s)', null, true);
            }
        }

        function hasChanges() {
            return userSectorRatingService.hasChanges();
        }

        function initialize() {

            sectorService.getSectorSet(false)
                .then(function (data) {
                    vm.sectorSet = data;
                });

            userService.getUserSet(false)
                .then(function (data) {
                    vm.userSet = data;
                });

            if (isNew) {
                // TODO For development enviroment, create test entity?
            }
            else {
                userSectorRatingService.getUserSectorRating($routeParams.Id)
                    .then(function (data) {
                        vm.userSectorRating = data;
                    })
                    .catch(function (error) {
                        // TODO User-friendly message?
                    });
            }
        };

        function isSaveDisabled() {
            return isSaving ||
                (!isNew && !userSectorRatingService.hasChanges());
        }

        function saveChanges() {

            if (isNew) {
                userSectorRatingService.createUserSectorRating(vm.userSectorRating);
            } else {
                // To be able to do concurrency check, RowVersion field needs to be send to server
				// Since breeze only sends the modified fields, a fake modification had to be applied to RowVersion field
                var rowVersion = vm.userSectorRating.RowVersion;
                vm.userSectorRating.RowVersion = '';
                vm.userSectorRating.RowVersion = rowVersion;
            }

            isSaving = true;
            userSectorRatingService.saveChanges()
                .then(function (result) {
                    $location.path('/UserSectorRating');
                })
                .catch(function (error) {
                    // Conflict (Concurrency exception)
                    if (error.status === '409') {
                        // TODO Try to recover!
                    }
                })
                .finally(function () {
                    isSaving = false;
                });
        }
    };
})();
