//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userResourcePoolIndexEditController';
    angular.module('main')
        .controller(controllerId, ['userResourcePoolIndexService',
            'resourcePoolIndexService',
            'userResourcePoolService',
            'logger',
            '$location',
            '$routeParams',
            userResourcePoolIndexEditController]);

    function userResourcePoolIndexEditController(userResourcePoolIndexService,
		resourcePoolIndexService,
		userResourcePoolService,
		logger,
		$location,
		$routeParams) {
        logger = logger.forSource(controllerId);

        var isNew = $location.path() === '/UserResourcePoolIndex/new';
        var isSaving = false;

        // Controller methods (alphabetically)
        var vm = this;
        vm.resourcePoolIndexSet = [];
        vm.userResourcePoolSet = [];
        vm.cancelChanges = cancelChanges;
        vm.isSaveDisabled = isSaveDisabled;
        vm.userResourcePoolIndex = null;
        vm.saveChanges = saveChanges;
        vm.hasChanges = hasChanges;

        initialize();

        /*** Implementations ***/

        function cancelChanges() {

            $location.path('/UserResourcePoolIndex');

            if (userResourcePoolIndexService.hasChanges()) {
                userResourcePoolIndexService.rejectChanges();
                logWarning('Discarded pending change(s)', null, true);
            }
        }

        function hasChanges() {
            return userResourcePoolIndexService.hasChanges();
        }

        function initialize() {

            resourcePoolIndexService.getResourcePoolIndexSet(false)
                .then(function (data) {
                    vm.resourcePoolIndexSet = data;
                });

            userResourcePoolService.getUserResourcePoolSet(false)
                .then(function (data) {
                    vm.userResourcePoolSet = data;
                });

            if (isNew) {
                // TODO For development enviroment, create test entity?
            }
            else {
                userResourcePoolIndexService.getUserResourcePoolIndex($routeParams.Id)
                    .then(function (data) {
                        vm.userResourcePoolIndex = data;
                    })
                    .catch(function (error) {
                        // TODO User-friendly message?
                    });
            }
        };

        function isSaveDisabled() {
            return isSaving ||
                (!isNew && !userResourcePoolIndexService.hasChanges());
        }

        function saveChanges() {

            if (isNew) {
                userResourcePoolIndexService.createUserResourcePoolIndex(vm.userResourcePoolIndex);
            } else {
                // To be able to do concurrency check, RowVersion field needs to be send to server
				// Since breeze only sends the modified fields, a fake modification had to be applied to RowVersion field
                var rowVersion = vm.userResourcePoolIndex.RowVersion;
                vm.userResourcePoolIndex.RowVersion = '';
                vm.userResourcePoolIndex.RowVersion = rowVersion;
            }

            isSaving = true;
            userResourcePoolIndexService.saveChanges()
                .then(function (result) {
                    $location.path('/UserResourcePoolIndex');
                })
                .catch(function (error) {
                    // Conflict (Concurrency exception)
                    if (error.status === '409') {
                        // TODO Try to recover!
                    }
                })
                .finally(function () {
                    isSaving = false;
                });
        }
    };
})();
