// <auto-generated />
namespace DataObjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class V0_11_9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V0_11_9));
        
        string IMigrationMetadata.Id
        {
            get { return "201405201412054_V0_11_9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
