// <auto-generated />
namespace DataObjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class V0_14_8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V0_14_8));
        
        string IMigrationMetadata.Id
        {
            get { return "201411282045150_V0_14_8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
