// <auto-generated />
namespace forCrowd.WealthEconomy.DataObjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _0780 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0780));
        
        string IMigrationMetadata.Id
        {
            get { return "201705281333459_0.78.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
