// <auto-generated />
namespace forCrowd.WealthEconomy.DataObjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _0790 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0790));
        
        string IMigrationMetadata.Id
        {
            get { return "201706051947532_0.79.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
