//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userElementFieldIndexListController';
    angular.module('main')
        .controller(controllerId, ['userElementFieldIndexService',
            'logger',
			userElementFieldIndexListController]);

    function userElementFieldIndexListController(userElementFieldIndexService,
        logger) {
        logger = logger.forSource(controllerId);

        var vm = this;
        vm.deleteUserElementFieldIndex = deleteUserElementFieldIndex;
        vm.userElementFieldIndexSet = [];

        initialize();

        function initialize() {
            getUserElementFieldIndexSet();
        };

        function deleteUserElementFieldIndex(userElementFieldIndex) {
            userElementFieldIndexService.deleteUserElementFieldIndex(userElementFieldIndex);

            userElementFieldIndexService.saveChanges()
                .then(function () {
                    vm.userElementFieldIndexSet.splice(vm.userElementFieldIndexSet.indexOf(userElementFieldIndex), 1);
                    logger.logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logger.logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getUserElementFieldIndexSet() {
            userElementFieldIndexService.getUserElementFieldIndexSet(false)
			    .then(function (data) {
                    vm.userElementFieldIndexSet = data;
                });
        }
    };
})();
