//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var serviceId = 'userResourcePoolService';
    angular.module('main')
        .factory(serviceId, ['dataContext', 'logger', userResourcePoolService]);

    function userResourcePoolService(dataContext, logger) {

        // Logger
        logger = logger.forSource(serviceId);
        var logError = logger.logError;
        var logSuccess = logger.logSuccess;
        var logWarning = logger.logWarning;

        // To determine whether the data will be fecthed from server or local
        var minimumDate = new Date(0);
        var fetchedOn = minimumDate;

        // Service methods (alphabetically)
        var service = {
            createUserResourcePool: createUserResourcePool,
            deleteUserResourcePool: deleteUserResourcePool,
            getChanges: getChanges,
            getChangesCount: getChangesCount,
            getUserResourcePoolSet: getUserResourcePoolSet,
            getUserResourcePool: getUserResourcePool,
            hasChanges: hasChanges,
            rejectChanges: rejectChanges,
            saveChanges: saveChanges
        };

        return service;

        /*** Implementations ***/

        function createUserResourcePool(userResourcePool) {
            return dataContext.manager.createEntity('UserResourcePool', userResourcePool);
        }

        function deleteUserResourcePool(userResourcePool) {
            userResourcePool.entityAspect.setDeleted();
        }

        function getChanges() {
            return dataContext.getChanges();
        }

        function getChangesCount() {
            return dataContext.getChangesCount();
        }

        function getUserResourcePoolSet(forceRefresh) {

            var count;
            if (forceRefresh) {
                if (dataContext.hasChanges()) {
                    count = dataContext.getChangesCount();
                    dataContext.rejectChanges(); // undo all unsaved changes!
                    logWarning('Discarded ' + count + ' pending change(s)', null, true);
                }
            }

            var query = breeze.EntityQuery
				.from("UserResourcePool")
				.expand(['User', 'ResourcePool'])
            ;

            // Fetch the data from server, in case if it's not fetched earlier or forced
            var fetchFromServer = fetchedOn === minimumDate || forceRefresh;

            // Prepare the query
            if (fetchFromServer) { // From remote
                query = query.using(breeze.FetchStrategy.FromServer)
                fetchedOn = new Date();
            }
            else { // From local
                query = query.using(breeze.FetchStrategy.FromLocalCache)
            }

            return dataContext.manager.executeQuery(query)
                .then(success).catch(failed);

            function success(response) {
                count = response.results.length;
                logSuccess('Got ' + count + ' userResourcePool(s)', response, true);
                return response.results;
            }

            function failed(error) {
                var message = error.message || "UserResourcePool query failed";
                logError(message, error, true);
            }
        }

        function getUserResourcePool(userResourcePoolId, forceRefresh) {
            return dataContext.manager.fetchEntityByKey("UserResourcePool", userResourcePoolId, !forceRefresh)
                .then(success).catch(failed);

            function success(result) {
                return result.entity;
            }

            function failed(error) {
                var message = error.message || "getUserResourcePool query failed";
                logError(message, error, true);
            }
        }

        function hasChanges() {
            return dataContext.hasChanges();
        }

        function rejectChanges() {
            dataContext.rejectChanges();
        }

        function saveChanges() {
            return dataContext.saveChanges();
        }
    }
})();
