//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'elementItemEditController';
    angular.module('main')
        .controller(controllerId, ['elementItemService',
            'elementService',
            'logger',
            '$location',
            '$routeParams',
            elementItemEditController]);

    function elementItemEditController(elementItemService,
		elementService,
		logger,
		$location,
		$routeParams) {
        logger = logger.forSource(controllerId);

        var isNew = $location.path() === '/manage/elementItem/new';
        var isSaving = false;

        // Controller methods (alphabetically)
        var vm = this;
        vm.elementSet = [];
        vm.cancelChanges = cancelChanges;
        vm.isSaveDisabled = isSaveDisabled;
        vm.entityErrors = [];
        vm.elementItem = null;
        vm.saveChanges = saveChanges;
        vm.hasChanges = hasChanges;

        initialize();

        /*** Implementations ***/

        function cancelChanges() {

            $location.path('/manage/elementItem');

            //if (elementItemService.hasChanges()) {
            //    elementItemService.rejectChanges();
            //    logWarning('Discarded pending change(s)', null, true);
            //}
        }

        function hasChanges() {
            return elementItemService.hasChanges();
        }

        function initialize() {

            elementService.getElementSet(false)
                .then(function (data) {
                    vm.elementSet = data;
                });

            if (isNew) {
                // TODO For development enviroment, create test entity?
            }
            else {
                elementItemService.getElementItem($routeParams.Id)
                    .then(function (data) {
                        vm.elementItem = data;
                    })
                    .catch(function (error) {
                        // TODO User-friendly message?
                    });
            }
        };

        function isSaveDisabled() {
            return isSaving ||
                (!isNew && !elementItemService.hasChanges());
        }

        function saveChanges() {

            if (isNew) {
                elementItemService.createElementItem(vm.elementItem);
            }

            isSaving = true;
            elementItemService.saveChanges()
                .then(function (result) {
                    $location.path('/manage/elementItem');
                })
                .catch(function (error) {
                    // Conflict (Concurrency exception)
                    if (typeof error.status !== 'undefined' && error.status === '409') {
                        // TODO Try to recover!
                    } else if (typeof error.entityErrors !== 'undefined') {
                        vm.entityErrors = error.entityErrors;
                    }
                })
                .finally(function () {
                    isSaving = false;
                });
        }
    };
})();
