//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userResourcePoolEditController';
    angular.module('main')
        .controller(controllerId, ['userResourcePoolService',
            'resourcePoolService',
            'userService',
            'logger',
            '$location',
            '$routeParams',
            userResourcePoolEditController]);

    function userResourcePoolEditController(userResourcePoolService,
		resourcePoolService,
		userService,
		logger,
		$location,
		$routeParams) {
        logger = logger.forSource(controllerId);

        var isNew = $location.path() === '/manage/userResourcePool/new';
        var isSaving = false;

        // Controller methods (alphabetically)
        var vm = this;
        vm.resourcePoolSet = [];
        vm.userSet = [];
        vm.cancelChanges = cancelChanges;
        vm.isSaveDisabled = isSaveDisabled;
        vm.entityErrors = [];
        vm.userResourcePool = null;
        vm.saveChanges = saveChanges;
        vm.hasChanges = hasChanges;

        initialize();

        /*** Implementations ***/

        function cancelChanges() {

            $location.path('/manage/userResourcePool');

            //if (userResourcePoolService.hasChanges()) {
            //    userResourcePoolService.rejectChanges();
            //    logWarning('Discarded pending change(s)', null, true);
            //}
        }

        function hasChanges() {
            return userResourcePoolService.hasChanges();
        }

        function initialize() {

            resourcePoolService.getResourcePoolSet(false)
                .then(function (data) {
                    vm.resourcePoolSet = data;
                });

            userService.getUserSet(false)
                .then(function (data) {
                    vm.userSet = data;
                });

            if (isNew) {
                // TODO For development enviroment, create test entity?
            }
            else {
                userResourcePoolService.getUserResourcePool($routeParams.Id)
                    .then(function (data) {
                        vm.userResourcePool = data;
                    })
                    .catch(function (error) {
                        // TODO User-friendly message?
                    });
            }
        };

        function isSaveDisabled() {
            return isSaving ||
                (!isNew && !userResourcePoolService.hasChanges());
        }

        function saveChanges() {

            if (isNew) {
                userResourcePoolService.createUserResourcePool(vm.userResourcePool);
            }

            isSaving = true;
            userResourcePoolService.saveChanges()
                .then(function (result) {
                    $location.path('/manage/userResourcePool');
                })
                .catch(function (error) {
                    // Conflict (Concurrency exception)
                    if (typeof error.status !== 'undefined' && error.status === '409') {
                        // TODO Try to recover!
                    } else if (typeof error.entityErrors !== 'undefined') {
                        vm.entityErrors = error.entityErrors;
                    }
                })
                .finally(function () {
                    isSaving = false;
                });
        }
    };
})();
