//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userLoginEditController';
    angular.module('main')
        .controller(controllerId, ['userLoginService',
            'userService',
            'logger',
            '$location',
            '$routeParams',
            userLoginEditController]);

    function userLoginEditController(userLoginService,
		userService,
		logger,
		$location,
		$routeParams) {
        logger = logger.forSource(controllerId);

        var isNew = $location.path() === '/manage/userLogin/new';
        var isSaving = false;

        // Controller methods (alphabetically)
        var vm = this;
        vm.userSet = [];
        vm.cancelChanges = cancelChanges;
        vm.isSaveDisabled = isSaveDisabled;
        vm.entityErrors = [];
        vm.userLogin = null;
        vm.saveChanges = saveChanges;
        vm.hasChanges = hasChanges;

        initialize();

        /*** Implementations ***/

        function cancelChanges() {

            $location.path('/manage/userLogin');

            //if (userLoginService.hasChanges()) {
            //    userLoginService.rejectChanges();
            //    logWarning('Discarded pending change(s)', null, true);
            //}
        }

        function hasChanges() {
            return userLoginService.hasChanges();
        }

        function initialize() {

            userService.getUserSet(false)
                .then(function (data) {
                    vm.userSet = data;
                });

            if (isNew) {
                // TODO For development enviroment, create test entity?
            }
            else {
                userLoginService.getUserLogin($routeParams.Id)
                    .then(function (data) {
                        vm.userLogin = data;
                    })
                    .catch(function (error) {
                        // TODO User-friendly message?
                    });
            }
        };

        function isSaveDisabled() {
            return isSaving ||
                (!isNew && !userLoginService.hasChanges());
        }

        function saveChanges() {

            if (isNew) {
                userLoginService.createUserLogin(vm.userLogin);
            } else {
                // To be able to do concurrency check, RowVersion field needs to be send to server
				// Since breeze only sends the modified fields, a fake modification had to be applied to RowVersion field
                var rowVersion = vm.userLogin.RowVersion;
                vm.userLogin.RowVersion = '';
                vm.userLogin.RowVersion = rowVersion;
            }

            isSaving = true;
            userLoginService.saveChanges()
                .then(function (result) {
                    $location.path('/manage/userLogin');
                })
                .catch(function (error) {
                    // Conflict (Concurrency exception)
                    if (error.status !== 'undefined' && error.status === '409') {
                        // TODO Try to recover!
                    } else if (error.entityErrors !== 'undefined') {
                        vm.entityErrors = error.entityErrors;
                    }
                })
                .finally(function () {
                    isSaving = false;
                });
        }
    };
})();
