using forCrowd.WealthEconomy.BusinessObjects.Entities;

namespace forCrowd.WealthEconomy.Facade
{
    using BusinessObjects;
    using DataObjects;
    using Framework;
    using Microsoft.AspNet.Identity;
    using System;
    using System.Data.Entity;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;

    public class AppUserManager : UserManager<User, int>
    {
        public AppUserManager(AppUserStore store, AppRoleStore appRoleStore) : base(store)
        {
            _roleStore = appRoleStore;
        }

        internal new AppUserStore Store => (AppUserStore)base.Store;
        private readonly AppRoleStore _roleStore;

        public override async Task<IdentityResult> AddPasswordAsync(int userId, string password)
        {
            // Add password
            var result = await base.AddPasswordAsync(userId, password);

            if (result.Succeeded)
            {
                // Get user
                var user = await FindByIdAsync(userId);

                user.HasPassword = true;

                await Store.Context.SaveChangesAsync();
            }

            return result;
        }

        public async Task AddSingleUseTokenAsync(User user)
        {
            user.SingleUseToken = Guid.NewGuid().ToString(); // Add single user token
            await Store.Context.SaveChangesAsync();
        }

        public override async Task<IdentityResult> ChangePasswordAsync(int userId, string currentPassword, string newPassword)
        {
            var result = await base.ChangePasswordAsync(userId, currentPassword, newPassword);

            if (result.Succeeded)
            {
                await Store.Context.SaveChangesAsync();
            }

            return result;
        }

        public async Task<IdentityResult> ChangeUserName(int userId, string userName)
        {
            var user = await FindByIdAsync(userId);

            user.UserName = userName;

            // Save
            await Store.Context.SaveChangesAsync();

            return IdentityResult.Success;
        }

        public override async Task<IdentityResult> ConfirmEmailAsync(int userId, string token)
        {
            var result = await base.ConfirmEmailAsync(userId, token);

            if (result.Succeeded)
            {
                // Update user's role
                await RemoveFromRoleAsync(userId, "Guest");
                await AddToRoleAsync(userId, "Regular");

                // Save
                await Store.Context.SaveChangesAsync();
            }

            return result;
        }

        [Obsolete("Use CreateUser function with string clientAppUrl signature")]
        public override Task<IdentityResult> CreateAsync(User user, string password)
        {
            throw new NotImplementedException("This method is obsolete");
        }

        /// <summary>
        /// Creates a regular local account
        /// </summary>
        /// <param name="user"></param>
        /// <param name="password"></param>
        /// <param name="autoGenerated"></param>
        /// <param name="clientAppUrl"></param>
        /// <returns></returns>
        public async Task<IdentityResult> CreateUserAsync(User user, string password, bool autoGenerated, string clientAppUrl)
        {
            IdentityResult result;

            if (password.IsNullOrDefault())
            {
                user.HasPassword = false;

                user.SingleUseToken = Guid.NewGuid().ToString(); // Add single user token

                result = await base.CreateAsync(user);
            }
            else
            {
                user.HasPassword = true;

                result = await base.CreateAsync(user, password);
            }

            if (result.Succeeded)
            {
                // Add to "Guest" role
                await Store.AddToRoleAsync(user, "Guest");

                // Save, so send confirmation email can use user.Id
                await Store.Context.SaveChangesAsync();

                // Whether this account was generated automatically (without using actually registering?), then just send a notification email
                if (autoGenerated)
                {
                    // Send "New guest account" notification email
                    await SendGuestAccountNotificationEmailAsync(user.Id);
                }
                else // Else, send a confirmation email to the user
                {
                    // Send confirmation email
                    await SendConfirmationEmailAsync(user, clientAppUrl);

                    // Save again
                    await Store.Context.SaveChangesAsync();
                }
            }

            return result;
        }

        /// <summary>
        /// Creates an account with external login and no password
        /// </summary>
        /// <param name="user"></param>
        /// <param name="userLoginInfo"></param>
        /// <returns></returns>
        public async Task<IdentityResult> CreateUserWithExternalLoginAsync(User user, UserLoginInfo userLoginInfo)
        {
            user.EmailConfirmed = true;

            user.HasPassword = false;

            user.SingleUseToken = Guid.NewGuid().ToString(); // Add single user token

            var result = await base.CreateAsync(user);

            if (result.Succeeded)
            {
                // Add to "Guest" role
                await Store.AddToRoleAsync(user, "Guest");

                // Add external login
                await Store.AddLoginAsync(user, userLoginInfo);

                // Save
                await Store.Context.SaveChangesAsync();

                // Send notification email
                await SendNewExternalLoginNotificationEmailAsync(user.Id);
            }

            return result;
        }

        public async Task<User> FindBySingleUseTokenAsync(string token)
        {
            // Search for the user
            var entity = await Users.SingleOrDefaultAsync(user => user.SingleUseToken == token);

            // Return null if there is no..
            if (entity == null)
                return null;

            // Remove token
            entity.SingleUseToken = null;

            // Save
            await Store.Context.SaveChangesAsync();

            // Return the user
            return entity;
        }

        public IQueryable<User> GetUserSet(bool live = true)
        {
            // Base
            var query = Store.Users;

            // Live?
            if (live)
            {
                query = query.Where(entity => !entity.DeletedOn.HasValue);
            }

            return query;
        }

        public IQueryable<Role> GetRoleSet(bool live = true)
        {
            // Base
            var query = _roleStore.Roles;

            // Live?
            if (live)
            {
                query = query.Where(entity => !entity.DeletedOn.HasValue);
            }

            return query;
        }

        /// <summary>
        /// For testing purposes
        /// </summary>
        /// <returns></returns>
        public string GetUniqueEmail()
        {
            var year = DateTime.Now.Year;
            var month = DateTime.Now.Month;
            var day = DateTime.Now.Day;
            var hour = DateTime.Now.Hour;
            var minute = DateTime.Now.Minute;
            var second = DateTime.Now.Second;
            return "user_" + year + month + day + "_" + hour + minute + second + "@forcrowd.org";
        }

        public async Task<string> GetUniqueUserNameFromEmail(string email)
        {
            var emailUsername = email.Substring(0, email.IndexOf("@", StringComparison.Ordinal));
            var userName = emailUsername;
            var count = 0;

            User user;
            do
            {
                if (count > 0) userName = emailUsername + count.ToString();
                user = await FindByNameAsync(userName);
                count++;
            } while (user != null);

            return userName;
        }

        public async Task<IdentityResult> LinkLoginAsync(User user, UserLoginInfo userLoginInfo)
        {
            // Email confirmed
            user.EmailConfirmed = true;

            user.SingleUseToken = Guid.NewGuid().ToString(); // Add single user token

            var result = await AddLoginAsync(user.Id, userLoginInfo);

            if (result.Succeeded)
            {
                await Store.Context.SaveChangesAsync();
            }

            return result;
        }

        public async Task ResendConfirmationEmailAsync(int userId, string clientAppUrl)
        {
            var user = await FindByIdAsync(userId);

            // Send confirmation email
            await SendConfirmationEmailAsync(user, clientAppUrl, true);

            // Save
            await Store.Context.SaveChangesAsync();
        }

        public override async Task<IdentityResult> ResetPasswordAsync(int userId, string token, string newPassword)
        {
            var result = await base.ResetPasswordAsync(userId, token, newPassword);

            if (result.Succeeded)
            {
                await Store.Context.SaveChangesAsync();
            }

            return result;
        }

        public async Task SendResetPasswordEmailAsync(int userId, string clientAppUrl)
        {
            // TODO Validation email

            var user = await FindByIdAsync(userId);

            // TODO Validation user

            var token = await GeneratePasswordResetTokenAsync(userId);
            var encodedToken = System.Net.WebUtility.UrlEncode(token);
            var resetPasswordUrl = $"{clientAppUrl}/app/account/reset-password;email={user.Email};token={encodedToken}";

            var subject = "Reset your password";

            var sbBody = new StringBuilder();
            sbBody.AppendLine("    <p>");
            sbBody.AppendLine("        <b>Wealth Economy - Reset Your Password</b><br />");
            sbBody.AppendLine("        <br />");
            sbBody.AppendFormat("        Username: {0}<br />", user.UserName);
            sbBody.AppendFormat("        Email: {0}<br />", user.Email);
            sbBody.AppendLine("        <br />");
            sbBody.AppendLine("        Please click the following link to reset your email password<br />");
            sbBody.AppendFormat("        <a href='{0}'>Reset your password</a>", resetPasswordUrl);
            sbBody.AppendLine("    </p>");
            sbBody.AppendLine("    <p>");
            sbBody.AppendLine("        Thanks,<br />");
            sbBody.AppendLine("        forCrowd Foundation");
            sbBody.AppendLine("    </p>");

            await SendEmailAsync(userId, subject, sbBody.ToString());
        }

        public async Task SendGuestAccountNotificationEmailAsync(int userId)
        {
            var subject = "New guest account";

            var user = await FindByIdAsync(userId);

            var sbBody = new StringBuilder();
            sbBody.AppendLine("    <p>");
            sbBody.AppendLine("        <b>Wealth Economy - New Guest Account</b><br />");
            sbBody.AppendLine("        <br />");
            sbBody.AppendFormat("        Email: {0}<br />", user.Email);
            sbBody.AppendLine("    </p>");
            sbBody.AppendLine("    <p>");
            sbBody.AppendLine("        Thanks,<br />");
            sbBody.AppendLine("        forCrowd Foundation");
            sbBody.AppendLine("    </p>");

            await SendEmailAsync(userId, subject, sbBody.ToString());
        }

        public async Task SendNewExternalLoginNotificationEmailAsync(int userId)
        {
            var subject = "New external login";

            var user = await FindByIdAsync(userId);

            var sbBody = new StringBuilder();
            sbBody.AppendLine("    <p>");
            sbBody.AppendLine("        <b>Wealth Economy - New External Login</b><br />");
            sbBody.AppendLine("        <br />");
            sbBody.AppendFormat("        Email: {0}<br />", user.Email);
            sbBody.AppendLine("    </p>");
            sbBody.AppendLine("    <p>");
            sbBody.AppendLine("        Thanks,<br />");
            sbBody.AppendLine("        forCrowd Foundation");
            sbBody.AppendLine("    </p>");

            await SendEmailAsync(userId, subject, sbBody.ToString());
        }

        [Obsolete("Use SetEmailAsync function with string clientAppUrl signature")]
        public override Task<IdentityResult> SetEmailAsync(int userId, string email)
        {
            throw new NotImplementedException("This method is obsolete");
        }

        public async Task<IdentityResult> SetEmailAsync(int userId, string email, string clientAppUrl)
        {
            var user = await FindByIdAsync(userId);

            var result = await base.SetEmailAsync(userId, email);

            if (result.Succeeded)
            {
                // Send confirmation email
                await SendConfirmationEmailAsync(user, clientAppUrl);

                // Save
                await Store.Context.SaveChangesAsync();
            }

            return result;
        }

        private async Task SendConfirmationEmailAsync(User user, string clientAppUrl, bool resend = false)
        {
            var token = await GenerateEmailConfirmationTokenAsync(user.Id);
            var encodedToken = System.Net.WebUtility.UrlEncode(token);
            var confirmEmailUrl = $"{clientAppUrl}/app/account/confirm-email;token={encodedToken}";

            var subject = "Confirm your email";
            if (resend) subject += " - Resend";

            var sbBody = new StringBuilder();
            sbBody.AppendLine("    <p>");
            sbBody.AppendLine("        <b>Wealth Economy - Confirm Your Email</b><br />");
            sbBody.AppendLine("        <br />");
            sbBody.AppendFormat("        Email: {0}<br />", user.Email);
            sbBody.AppendLine("        <br />");
            sbBody.AppendLine("        Please click the following link to confirm your email address<br />");
            sbBody.AppendFormat("        <a href='{0}'>Confirm your email address</a>", confirmEmailUrl);
            sbBody.AppendLine("    </p>");
            sbBody.AppendLine("    <p>");
            sbBody.AppendLine("        Thanks,<br />");
            sbBody.AppendLine("        forCrowd Foundation");
            sbBody.AppendLine("    </p>");

            // Send the email
            await SendEmailAsync(user.Id, subject, sbBody.ToString());

            // Set email confirmation sent on
            user.EmailConfirmationSentOn = DateTime.UtcNow;
        }
    }
}