//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects.Dto
{
    using System;
    
    public class OrganizationDto
    {
        public int Id { get; set; }
        public byte SectorId { get; set; }
        public string Name { get; set; }
        public decimal ProductionCost { get; set; }
        public decimal SalesPrice { get; set; }
        public short LicenseId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    	
    	public Organization ToBusinessObject()
    	{
    		return new Organization()
    		{
    			Id = Id, 
    			SectorId = SectorId, 
    			Name = Name, 
    			ProductionCost = ProductionCost, 
    			SalesPrice = SalesPrice, 
    			LicenseId = LicenseId, 
    			CreatedOn = CreatedOn, 
    			ModifiedOn = ModifiedOn, 
    			DeletedOn = DeletedOn
    		};
    	}
    }
}
