//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects.Dto
{
    using System;
    
    public class ResourcePoolOrganizationDto
    {
        public int Id { get; set; }
        public int ResourcePoolId { get; set; }
        public int OrganizationId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    	
    	public ResourcePoolOrganization ToBusinessObject()
    	{
    		return new ResourcePoolOrganization()
    		{
    			Id = Id, 
    			ResourcePoolId = ResourcePoolId, 
    			OrganizationId = OrganizationId, 
    			CreatedOn = CreatedOn, 
    			ModifiedOn = ModifiedOn, 
    			DeletedOn = DeletedOn
    		};
    	}
    }
}
