//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects.Dto
{
    using System;
    using System.ComponentModel.DataAnnotations;
    
    public class UserDto
    {
    	[Required]
        public int Id { get; set; }
    	[Required]
        public string Email { get; set; }
    	[Required]
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
    	[Required]
        public UserAccountType UserAccountTypeId { get; set; }
        public string Notes { get; set; }
    	[Required]
        public System.DateTime CreatedOn { get; set; }
    	[Required]
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    	
    	public User ToBusinessObject()
    	{
    		return new User()
    		{
    			Id = Id, 
    			Email = Email, 
    			Password = Password, 
    			FirstName = FirstName, 
    			MiddleName = MiddleName, 
    			LastName = LastName, 
    			UserAccountTypeId = UserAccountTypeId, 
    			Notes = Notes, 
    			CreatedOn = CreatedOn, 
    			ModifiedOn = ModifiedOn, 
    			DeletedOn = DeletedOn
    		};
    	}
    }
}
