//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'elementItemElementFieldListController';
    angular.module('main')
        .controller(controllerId, ['elementItemElementFieldService',
            'logger',
			elementItemElementFieldListController]);

    function elementItemElementFieldListController(elementItemElementFieldService,
        logger) {
        logger = logger.forSource(controllerId);

        var vm = this;
        vm.deleteElementItemElementField = deleteElementItemElementField;
        vm.elementItemElementFieldSet = [];

        initialize();

        function initialize() {
            getElementItemElementFieldSet();
        };

        function deleteElementItemElementField(elementItemElementField) {
            elementItemElementFieldService.deleteElementItemElementField(elementItemElementField);

            elementItemElementFieldService.saveChanges()
                .then(function () {
                    vm.elementItemElementFieldSet.splice(vm.elementItemElementFieldSet.indexOf(elementItemElementField), 1);
                    logger.logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logger.logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getElementItemElementFieldSet() {
            elementItemElementFieldService.getElementItemElementFieldSet(false)
			    .then(function (data) {
                    vm.elementItemElementFieldSet = data;
                });
        }
    };
})();
