//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'organizationElementListController';
    angular.module('main')
        .controller(controllerId, ['organizationElementService',
            'logger',
			organizationElementListController]);

    function organizationElementListController(organizationElementService,
        logger) {
        logger = logger.forSource(controllerId);

        var vm = this;
        vm.deleteOrganizationElement = deleteOrganizationElement;
        vm.organizationElementSet = [];

        initialize();

        function initialize() {
            getOrganizationElementSet();
        };

        function deleteOrganizationElement(organizationElement) {
            organizationElementService.deleteOrganizationElement(organizationElement);

            organizationElementService.saveChanges()
                .then(function () {
                    vm.organizationElementSet.splice(vm.organizationElementSet.indexOf(organizationElement), 1);
                    logger.logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logger.logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getOrganizationElementSet() {
            organizationElementService.getOrganizationElementSet(false)
			    .then(function (data) {
                    vm.organizationElementSet = data;
                });
        }
    };
})();
