//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'organizationElementItemListController';
    angular.module('main')
        .controller(controllerId, ['organizationElementItemService',
            'logger',
			organizationElementItemListController]);

    function organizationElementItemListController(organizationElementItemService,
        logger) {
        logger = logger.forSource(controllerId);

        var vm = this;
        vm.deleteOrganizationElementItem = deleteOrganizationElementItem;
        vm.organizationElementItemSet = [];

        initialize();

        function initialize() {
            getOrganizationElementItemSet();
        };

        function deleteOrganizationElementItem(organizationElementItem) {
            organizationElementItemService.deleteOrganizationElementItem(organizationElementItem);

            organizationElementItemService.saveChanges()
                .then(function () {
                    vm.organizationElementItemSet.splice(vm.organizationElementItemSet.indexOf(organizationElementItem), 1);
                    logger.logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logger.logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getOrganizationElementItemSet() {
            organizationElementItemService.getOrganizationElementItemSet(false)
			    .then(function (data) {
                    vm.organizationElementItemSet = data;
                });
        }
    };
})();
