//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'resourcePoolOrganizationElementListController';
    angular.module('main')
        .controller(controllerId, ['resourcePoolOrganizationElementService',
            'logger',
			resourcePoolOrganizationElementListController]);

    function resourcePoolOrganizationElementListController(resourcePoolOrganizationElementService,
        logger) {
        logger = logger.forSource(controllerId);

        var vm = this;
        vm.deleteResourcePoolOrganizationElement = deleteResourcePoolOrganizationElement;
        vm.resourcePoolOrganizationElementSet = [];

        initialize();

        function initialize() {
            getResourcePoolOrganizationElementSet();
        };

        function deleteResourcePoolOrganizationElement(resourcePoolOrganizationElement) {
            resourcePoolOrganizationElementService.deleteResourcePoolOrganizationElement(resourcePoolOrganizationElement);

            resourcePoolOrganizationElementService.saveChanges()
                .then(function () {
                    vm.resourcePoolOrganizationElementSet.splice(vm.resourcePoolOrganizationElementSet.indexOf(resourcePoolOrganizationElement), 1);
                    logger.logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logger.logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getResourcePoolOrganizationElementSet() {
            resourcePoolOrganizationElementService.getResourcePoolOrganizationElementSet(false)
			    .then(function (data) {
                    vm.resourcePoolOrganizationElementSet = data;
                });
        }
    };
})();
