//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'roleListController';
    angular.module('main')
        .controller(controllerId, ['roleService',
            'logger',
			roleListController]);

    function roleListController(roleService,
        logger) {
        logger = logger.forSource(controllerId);

        var vm = this;
        vm.deleteRole = deleteRole;
        vm.roleSet = [];

        initialize();

        function initialize() {
            getRoleSet();
        };

        function deleteRole(role) {
            roleService.deleteRole(role);

            roleService.saveChanges()
                .then(function () {
                    vm.roleSet.splice(vm.roleSet.indexOf(role), 1);
                    logger.logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logger.logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getRoleSet() {
            roleService.getRoleSet(false)
			    .then(function (data) {
                    vm.roleSet = data;
                });
        }
    };
})();
