//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userElementItemElementFieldListController';
    angular.module('main')
        .controller(controllerId, ['userElementItemElementFieldService',
            'logger',
			userElementItemElementFieldListController]);

    function userElementItemElementFieldListController(userElementItemElementFieldService,
        logger) {
        logger = logger.forSource(controllerId);

        var vm = this;
        vm.deleteUserElementItemElementField = deleteUserElementItemElementField;
        vm.userElementItemElementFieldSet = [];

        initialize();

        function initialize() {
            getUserElementItemElementFieldSet();
        };

        function deleteUserElementItemElementField(userElementItemElementField) {
            userElementItemElementFieldService.deleteUserElementItemElementField(userElementItemElementField);

            userElementItemElementFieldService.saveChanges()
                .then(function () {
                    vm.userElementItemElementFieldSet.splice(vm.userElementItemElementFieldSet.indexOf(userElementItemElementField), 1);
                    logger.logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logger.logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getUserElementItemElementFieldSet() {
            userElementItemElementFieldService.getUserElementItemElementFieldSet(false)
			    .then(function (data) {
                    vm.userElementItemElementFieldSet = data;
                });
        }
    };
})();
