//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userResourcePoolIndexListController';
    angular.module('main')
        .controller(controllerId, ['userResourcePoolIndexService',
            'logger',
			userResourcePoolIndexListController]);

    function userResourcePoolIndexListController(userResourcePoolIndexService,
        logger) {
        logger = logger.forSource(controllerId);

        var vm = this;
        vm.deleteUserResourcePoolIndex = deleteUserResourcePoolIndex;
        vm.userResourcePoolIndexSet = [];

        initialize();

        function initialize() {
            getUserResourcePoolIndexSet();
        };

        function deleteUserResourcePoolIndex(userResourcePoolIndex) {
            userResourcePoolIndexService.deleteUserResourcePoolIndex(userResourcePoolIndex);

            userResourcePoolIndexService.saveChanges()
                .then(function () {
                    vm.userResourcePoolIndexSet.splice(vm.userResourcePoolIndexSet.indexOf(userResourcePoolIndex), 1);
                    logger.logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logger.logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getUserResourcePoolIndexSet() {
            userResourcePoolIndexService.getUserResourcePoolIndexSet(false)
			    .then(function (data) {
                    vm.userResourcePoolIndexSet = data;
                });
        }
    };
})();
