//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userElementCellListController';
    angular.module('main')
        .controller(controllerId, ['userElementCellService',
            'logger',
			userElementCellListController]);

    function userElementCellListController(userElementCellService,
        logger) {
        logger = logger.forSource(controllerId);

        var vm = this;
        vm.deleteUserElementCell = deleteUserElementCell;
        vm.userElementCellSet = [];

        initialize();

        function initialize() {
            getUserElementCellSet();
        };

        function deleteUserElementCell(userElementCell) {
            userElementCellService.deleteUserElementCell(userElementCell);

            userElementCellService.saveChanges()
                .then(function () {
                    vm.userElementCellSet.splice(vm.userElementCellSet.indexOf(userElementCell), 1);
                    logger.logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logger.logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getUserElementCellSet() {
            userElementCellService.getUserElementCellSet(false)
			    .then(function (data) {
                    vm.userElementCellSet = data;
                });
        }
    };
})();
