//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userElementItemListController';
    angular.module('main')
        .controller(controllerId, ['userElementItemService',
            'logger',
			userElementItemListController]);

    function userElementItemListController(userElementItemService,
        logger) {
        logger = logger.forSource(controllerId);

        var vm = this;
        vm.deleteUserElementItem = deleteUserElementItem;
        vm.userElementItemSet = [];

        initialize();

        function initialize() {
            getUserElementItemSet();
        };

        function deleteUserElementItem(userElementItem) {
            userElementItemService.deleteUserElementItem(userElementItem);

            userElementItemService.saveChanges()
                .then(function () {
                    vm.userElementItemSet.splice(vm.userElementItemSet.indexOf(userElementItem), 1);
                    logger.logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logger.logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getUserElementItemSet() {
            userElementItemService.getUserElementItemSet(false)
			    .then(function (data) {
                    vm.userElementItemSet = data;
                });
        }
    };
})();
