//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userResourcePoolIndexElementItemListController';
    angular.module('main')
        .controller(controllerId, ['userResourcePoolIndexElementItemService',
            'logger',
			userResourcePoolIndexElementItemListController]);

    function userResourcePoolIndexElementItemListController(userResourcePoolIndexElementItemService,
        logger) {
        logger = logger.forSource(controllerId);

        var vm = this;
        vm.deleteUserResourcePoolIndexElementItem = deleteUserResourcePoolIndexElementItem;
        vm.userResourcePoolIndexElementItemSet = [];

        initialize();

        function initialize() {
            getUserResourcePoolIndexElementItemSet();
        };

        function deleteUserResourcePoolIndexElementItem(userResourcePoolIndexElementItem) {
            userResourcePoolIndexElementItemService.deleteUserResourcePoolIndexElementItem(userResourcePoolIndexElementItem);

            userResourcePoolIndexElementItemService.saveChanges()
                .then(function () {
                    vm.userResourcePoolIndexElementItemSet.splice(vm.userResourcePoolIndexElementItemSet.indexOf(userResourcePoolIndexElementItem), 1);
                    logger.logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logger.logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getUserResourcePoolIndexElementItemSet() {
            userResourcePoolIndexElementItemService.getUserResourcePoolIndexElementItemSet(false)
			    .then(function (data) {
                    vm.userResourcePoolIndexElementItemSet = data;
                });
        }
    };
})();
