//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userRoleListController';
    angular.module('main')
        .controller(controllerId, ['userRoleService',
            'logger',
			userRoleListController]);

    function userRoleListController(userRoleService,
        logger) {
        logger = logger.forSource(controllerId);

        var vm = this;
        vm.deleteUserRole = deleteUserRole;
        vm.userRoleSet = [];

        initialize();

        function initialize() {
            getUserRoleSet();
        };

        function deleteUserRole(userRole) {
            userRoleService.deleteUserRole(userRole);

            userRoleService.saveChanges()
                .then(function () {
                    vm.userRoleSet.splice(vm.userRoleSet.indexOf(userRole), 1);
                    logger.logSuccess("Hooray we saved", null, true);
                })
                .catch(function (error) {
                    logger.logError("Boooo, we failed: " + error.message, null, true);
                    // Todo: more sophisticated recovery. 
                    // Here we just blew it all away and start over
                    // refresh();
                })
        };

        function getUserRoleSet() {
            userRoleService.getUserRoleSet(false)
			    .then(function (data) {
                    vm.userRoleSet = data;
                });
        }
    };
})();
