/*
EntityFramework.dll + EntityFramework.SqlServer.dll files under
C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE folder
were replaced with Entity Framework 6.1 versions.
v0.10.9
SH - 09 May '14
*/


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    document.write('\
	\
    <script src="/App/services/generated/elementService.js?v=029"></script>\
    <script src="/App/controllers/manage/list/elementListController.js?v=027"></script>\
    <script src="/App/controllers/manage/edit/elementEditController.js?v=027"></script>\
	\
    <script src="/App/services/generated/elementCellService.js?v=029"></script>\
    <script src="/App/controllers/manage/list/elementCellListController.js?v=027"></script>\
    <script src="/App/controllers/manage/edit/elementCellEditController.js?v=027"></script>\
	\
    <script src="/App/services/generated/elementFieldService.js?v=029"></script>\
    <script src="/App/controllers/manage/list/elementFieldListController.js?v=027"></script>\
    <script src="/App/controllers/manage/edit/elementFieldEditController.js?v=027"></script>\
	\
    <script src="/App/services/generated/elementItemService.js?v=029"></script>\
    <script src="/App/controllers/manage/list/elementItemListController.js?v=027"></script>\
    <script src="/App/controllers/manage/edit/elementItemEditController.js?v=027"></script>\
	\
    <script src="/App/services/generated/resourcePoolService.js?v=029"></script>\
    <script src="/App/controllers/manage/list/resourcePoolListController.js?v=027"></script>\
    <script src="/App/controllers/manage/edit/resourcePoolEditController.js?v=027"></script>\
	\
    <script src="/App/services/generated/roleService.js?v=029"></script>\
    <script src="/App/controllers/manage/list/roleListController.js?v=027"></script>\
    <script src="/App/controllers/manage/edit/roleEditController.js?v=027"></script>\
	\
    <script src="/App/services/generated/userService.js?v=029"></script>\
    <script src="/App/controllers/manage/list/userListController.js?v=027"></script>\
    <script src="/App/controllers/manage/edit/userEditController.js?v=027"></script>\
	\
    <script src="/App/services/generated/userClaimService.js?v=029"></script>\
    <script src="/App/controllers/manage/list/userClaimListController.js?v=027"></script>\
    <script src="/App/controllers/manage/edit/userClaimEditController.js?v=027"></script>\
	\
    <script src="/App/services/generated/userElementCellService.js?v=029"></script>\
    <script src="/App/controllers/manage/list/userElementCellListController.js?v=027"></script>\
    <script src="/App/controllers/manage/edit/userElementCellEditController.js?v=027"></script>\
	\
    <script src="/App/services/generated/userElementFieldService.js?v=029"></script>\
    <script src="/App/controllers/manage/list/userElementFieldListController.js?v=027"></script>\
    <script src="/App/controllers/manage/edit/userElementFieldEditController.js?v=027"></script>\
	\
    <script src="/App/services/generated/userLoginService.js?v=029"></script>\
    <script src="/App/controllers/manage/list/userLoginListController.js?v=027"></script>\
    <script src="/App/controllers/manage/edit/userLoginEditController.js?v=027"></script>\
	\
    <script src="/App/services/generated/userResourcePoolService.js?v=029"></script>\
    <script src="/App/controllers/manage/list/userResourcePoolListController.js?v=027"></script>\
    <script src="/App/controllers/manage/edit/userResourcePoolEditController.js?v=027"></script>\
	\
    <script src="/App/services/generated/userRoleService.js?v=029"></script>\
    <script src="/App/controllers/manage/list/userRoleListController.js?v=027"></script>\
    <script src="/App/controllers/manage/edit/userRoleEditController.js?v=027"></script>\
	\
\
');

})();
