/*
EntityFramework.dll + EntityFramework.SqlServer.dll files under
C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE folder
were replaced with Entity Framework 6.1 versions.
v0.10.9
SH - 09 May '14
*/


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    document.write('\
	\
    <ul class="dropdown-menu">\
    <li><a href="/manage/element">Element</a></li>\
    <li><a href="/manage/elementCell">Element Cell</a></li>\
    <li><a href="/manage/elementField">Element Field</a></li>\
    <li><a href="/manage/elementFieldIndex">Element Field Index</a></li>\
    <li><a href="/manage/elementItem">Element Item</a></li>\
    <li><a href="/manage/resourcePool">CMRP</a></li>\
    <li><a href="/manage/role">Role</a></li>\
    <li><a href="/manage/user">User</a></li>\
    <li><a href="/manage/userClaim">User Claim</a></li>\
    <li><a href="/manage/userElementCell">User Element Cell</a></li>\
    <li><a href="/manage/userElementFieldIndex">User Element Field Index</a></li>\
    <li><a href="/manage/userLogin">User Login</a></li>\
    <li><a href="/manage/userResourcePool">User CMRP</a></li>\
    <li><a href="/manage/userRole">User Role</a></li>\
    </ul>\
\
');

})();
