

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    document.write('\
	\
    <ul class="dropdown-menu">\
    <li><a href="/manage/generated/element">Element</a></li>\
    <li><a href="/manage/generated/elementCell">Element Cell</a></li>\
    <li><a href="/manage/generated/elementField">Element Field</a></li>\
    <li><a href="/manage/generated/elementItem">Element Item</a></li>\
    <li><a href="/manage/generated/resourcePool">CMRP</a></li>\
    <li><a href="/manage/generated/role">Role</a></li>\
    <li><a href="/manage/generated/user">User</a></li>\
    <li><a href="/manage/generated/userClaim">User Claim</a></li>\
    <li><a href="/manage/generated/userElementCell">User Element Cell</a></li>\
    <li><a href="/manage/generated/userElementField">User Element Field Index</a></li>\
    <li><a href="/manage/generated/userLogin">User Login</a></li>\
    <li><a href="/manage/generated/userResourcePool">User CMRP</a></li>\
    <li><a href="/manage/generated/userRole">User Role</a></li>\
    </ul>\
\
');

})();
