

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    document.write('\
	\
    <script src="/App/factories/generated/elementFactory.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/list/ElementListController.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/edit/ElementEditController.js?v=0.43"></script>\
	\
    <script src="/App/factories/generated/elementCellFactory.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/list/ElementCellListController.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/edit/ElementCellEditController.js?v=0.43"></script>\
	\
    <script src="/App/factories/generated/elementFieldFactory.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/list/ElementFieldListController.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/edit/ElementFieldEditController.js?v=0.43"></script>\
	\
    <script src="/App/factories/generated/elementItemFactory.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/list/ElementItemListController.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/edit/ElementItemEditController.js?v=0.43"></script>\
	\
    <script src="/App/factories/generated/resourcePoolFactory.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/list/ResourcePoolListController.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/edit/ResourcePoolEditController.js?v=0.43"></script>\
	\
    <script src="/App/factories/generated/roleFactory.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/list/RoleListController.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/edit/RoleEditController.js?v=0.43"></script>\
	\
    <script src="/App/factories/generated/userFactory.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/list/UserListController.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/edit/UserEditController.js?v=0.43"></script>\
	\
    <script src="/App/factories/generated/userClaimFactory.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/list/UserClaimListController.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/edit/UserClaimEditController.js?v=0.43"></script>\
	\
    <script src="/App/factories/generated/userElementCellFactory.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/list/UserElementCellListController.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/edit/UserElementCellEditController.js?v=0.43"></script>\
	\
    <script src="/App/factories/generated/userElementFieldFactory.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/list/UserElementFieldListController.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/edit/UserElementFieldEditController.js?v=0.43"></script>\
	\
    <script src="/App/factories/generated/userLoginFactory.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/list/UserLoginListController.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/edit/UserLoginEditController.js?v=0.43"></script>\
	\
    <script src="/App/factories/generated/userResourcePoolFactory.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/list/UserResourcePoolListController.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/edit/UserResourcePoolEditController.js?v=0.43"></script>\
	\
    <script src="/App/factories/generated/userRoleFactory.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/list/UserRoleListController.js?v=0.43"></script>\
    <script src="/App/controllers/manage/generated/edit/UserRoleEditController.js?v=0.43"></script>\
	\
\
');

})();
