//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects.Metadata
{
    using System;
    using System.ComponentModel.DataAnnotations;
    
    public class OrganizationMetadata
    {
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Display(Name = "User")]
        public int UserId { get; set; }

        [Display(Name = "Sector")]
        public byte SectorId { get; set; }
    
        [Display(Name = "Organization")]
        public string Name { get; set; }
    
        [Display(Name = "Production Cost")]
        public decimal ProductionCost { get; set; }
    
        [Display(Name = "Sales Price")]
        public decimal SalesPrice { get; set; }
    
        [Display(Name = "License")]
        public short LicenseId { get; set; }
    
        [Display(Name = "Number of Sales")]
        public int NumberOfSales { get; set; }
    
        [Display(Name = "Created On")]
        public System.DateTime CreatedOn { get; set; }
    
        [Display(Name = "Modified On")]
        public System.DateTime ModifiedOn { get; set; }
    
        [Display(Name = "Deleted On")]
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
    }
}
