//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects.Metadata
{
    using System;
    using System.ComponentModel.DataAnnotations;
    
    public class UserMetadata
    {
        [Display(Name = "Id")]
        public int Id { get; set; }
    
        [Display(Name = "Email")]
        public string Email { get; set; }
    
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
    
        [Display(Name = "Middle Name")]
        public string MiddleName { get; set; }
    
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "CMRP Rate")]
        public string ResourcePoolRate { get; set; }
    
        [Display(Name = "CreatedOn")]
        public System.DateTime CreatedOn { get; set; }
    
        [Display(Name = "ModifiedOn")]
        public System.DateTime ModifiedOn { get; set; }
    
        [Display(Name = "DeletedOn")]
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
    }
}
