
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects
{
    using BusinessObjects;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WealthEconomyEntities : DbContext
    {
        public WealthEconomyEntities()
            : base("name=WealthEconomyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<License> LicenseSet { get; set; }
        public virtual DbSet<Organization> OrganizationSet { get; set; }
        public virtual DbSet<Sector> SectorSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<UserLicenseRating> UserLicenseRatingSet { get; set; }
        public virtual DbSet<UserSectorRating> UserSectorRatingSet { get; set; }
        public virtual DbSet<ResourcePool> ResourcePoolSet { get; set; }
        public virtual DbSet<ResourcePoolOrganization> ResourcePoolOrganizationSet { get; set; }
        public virtual DbSet<UserResourcePool> UserResourcePoolSet { get; set; }
        public virtual DbSet<UserResourcePoolOrganization> UserResourcePoolOrganizationSet { get; set; }
    }
}
