//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'organizationElementEditController';
    angular.module('main')
        .controller(controllerId, ['organizationElementService',
            'elementService',
            'organizationService',
            'logger',
            '$location',
            '$routeParams',
            organizationElementEditController]);

    function organizationElementEditController(organizationElementService,
		elementService,
		organizationService,
		logger,
		$location,
		$routeParams) {
        logger = logger.forSource(controllerId);

        var isNew = $location.path() === '/manage/organizationElement/new';
        var isSaving = false;

        // Controller methods (alphabetically)
        var vm = this;
        vm.elementSet = [];
        vm.organizationSet = [];
        vm.cancelChanges = cancelChanges;
        vm.isSaveDisabled = isSaveDisabled;
        vm.organizationElement = null;
        vm.saveChanges = saveChanges;
        vm.hasChanges = hasChanges;

        initialize();

        /*** Implementations ***/

        function cancelChanges() {

            $location.path('/manage/organizationElement');

            if (organizationElementService.hasChanges()) {
                organizationElementService.rejectChanges();
                logWarning('Discarded pending change(s)', null, true);
            }
        }

        function hasChanges() {
            return organizationElementService.hasChanges();
        }

        function initialize() {

            elementService.getElementSet(false)
                .then(function (data) {
                    vm.elementSet = data;
                });

            organizationService.getOrganizationSet(false)
                .then(function (data) {
                    vm.organizationSet = data;
                });

            if (isNew) {
                // TODO For development enviroment, create test entity?
            }
            else {
                organizationElementService.getOrganizationElement($routeParams.Id)
                    .then(function (data) {
                        vm.organizationElement = data;
                    })
                    .catch(function (error) {
                        // TODO User-friendly message?
                    });
            }
        };

        function isSaveDisabled() {
            return isSaving ||
                (!isNew && !organizationElementService.hasChanges());
        }

        function saveChanges() {

            if (isNew) {
                organizationElementService.createOrganizationElement(vm.organizationElement);
            } else {
                // To be able to do concurrency check, RowVersion field needs to be send to server
				// Since breeze only sends the modified fields, a fake modification had to be applied to RowVersion field
                var rowVersion = vm.organizationElement.RowVersion;
                vm.organizationElement.RowVersion = '';
                vm.organizationElement.RowVersion = rowVersion;
            }

            isSaving = true;
            organizationElementService.saveChanges()
                .then(function (result) {
                    $location.path('/manage/organizationElement');
                })
                .catch(function (error) {
                    // Conflict (Concurrency exception)
                    if (error.status === '409') {
                        // TODO Try to recover!
                    }
                })
                .finally(function () {
                    isSaving = false;
                });
        }
    };
})();
