//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'resourcePoolIndexEditController';
    angular.module('main')
        .controller(controllerId, ['resourcePoolIndexService',
            'resourcePoolService',
            'logger',
            '$location',
            '$routeParams',
            resourcePoolIndexEditController]);

    function resourcePoolIndexEditController(resourcePoolIndexService,
		resourcePoolService,
		logger,
		$location,
		$routeParams) {
        logger = logger.forSource(controllerId);

        var isNew = $location.path() === '/manage/resourcePoolIndex/new';
        var isSaving = false;

        // Controller methods (alphabetically)
        var vm = this;
        vm.resourcePoolSet = [];
        vm.cancelChanges = cancelChanges;
        vm.isSaveDisabled = isSaveDisabled;
        vm.resourcePoolIndex = null;
        vm.saveChanges = saveChanges;
        vm.hasChanges = hasChanges;

        initialize();

        /*** Implementations ***/

        function cancelChanges() {

            $location.path('/manage/resourcePoolIndex');

            if (resourcePoolIndexService.hasChanges()) {
                resourcePoolIndexService.rejectChanges();
                logWarning('Discarded pending change(s)', null, true);
            }
        }

        function hasChanges() {
            return resourcePoolIndexService.hasChanges();
        }

        function initialize() {

            resourcePoolService.getResourcePoolSet(false)
                .then(function (data) {
                    vm.resourcePoolSet = data;
                });

            if (isNew) {
                // TODO For development enviroment, create test entity?
            }
            else {
                resourcePoolIndexService.getResourcePoolIndex($routeParams.Id)
                    .then(function (data) {
                        vm.resourcePoolIndex = data;
                    })
                    .catch(function (error) {
                        // TODO User-friendly message?
                    });
            }
        };

        function isSaveDisabled() {
            return isSaving ||
                (!isNew && !resourcePoolIndexService.hasChanges());
        }

        function saveChanges() {

            if (isNew) {
                resourcePoolIndexService.createResourcePoolIndex(vm.resourcePoolIndex);
            } else {
                // To be able to do concurrency check, RowVersion field needs to be send to server
				// Since breeze only sends the modified fields, a fake modification had to be applied to RowVersion field
                var rowVersion = vm.resourcePoolIndex.RowVersion;
                vm.resourcePoolIndex.RowVersion = '';
                vm.resourcePoolIndex.RowVersion = rowVersion;
            }

            isSaving = true;
            resourcePoolIndexService.saveChanges()
                .then(function (result) {
                    $location.path('/manage/resourcePoolIndex');
                })
                .catch(function (error) {
                    // Conflict (Concurrency exception)
                    if (error.status === '409') {
                        // TODO Try to recover!
                    }
                })
                .finally(function () {
                    isSaving = false;
                });
        }
    };
})();
