//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'roleEditController';
    angular.module('main')
        .controller(controllerId, ['roleService',
            'logger',
            '$location',
            '$routeParams',
            roleEditController]);

    function roleEditController(roleService,
		logger,
		$location,
		$routeParams) {
        logger = logger.forSource(controllerId);

        var isNew = $location.path() === '/manage/role/new';
        var isSaving = false;

        // Controller methods (alphabetically)
        var vm = this;
        vm.cancelChanges = cancelChanges;
        vm.isSaveDisabled = isSaveDisabled;
        vm.entityErrors = [];
        vm.role = null;
        vm.saveChanges = saveChanges;
        vm.hasChanges = hasChanges;

        initialize();

        /*** Implementations ***/

        function cancelChanges() {

            $location.path('/manage/role');

            if (roleService.hasChanges()) {
                roleService.rejectChanges();
                logWarning('Discarded pending change(s)', null, true);
            }
        }

        function hasChanges() {
            return roleService.hasChanges();
        }

        function initialize() {

            if (isNew) {
                // TODO For development enviroment, create test entity?
            }
            else {
                roleService.getRole($routeParams.Id)
                    .then(function (data) {
                        vm.role = data;
                    })
                    .catch(function (error) {
                        // TODO User-friendly message?
                    });
            }
        };

        function isSaveDisabled() {
            return isSaving ||
                (!isNew && !roleService.hasChanges());
        }

        function saveChanges() {

            if (isNew) {
                roleService.createRole(vm.role);
            } else {
                // To be able to do concurrency check, RowVersion field needs to be send to server
				// Since breeze only sends the modified fields, a fake modification had to be applied to RowVersion field
                var rowVersion = vm.role.RowVersion;
                vm.role.RowVersion = '';
                vm.role.RowVersion = rowVersion;
            }

            isSaving = true;
            roleService.saveChanges()
                .then(function (result) {
                    $location.path('/manage/role');
                })
                .catch(function (error) {
                    // Conflict (Concurrency exception)
                    if (error.status !== 'undefined' && error.status === '409') {
                        // TODO Try to recover!
                    } else if (error.entityErrors !== 'undefined') {
                        vm.entityErrors = error.entityErrors;
                    }
                })
                .finally(function () {
                    isSaving = false;
                });
        }
    };
})();
