//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userElementItemEditController';
    angular.module('main')
        .controller(controllerId, ['userElementItemService',
            'elementItemService',
            'userService',
            'logger',
            '$location',
            '$routeParams',
            userElementItemEditController]);

    function userElementItemEditController(userElementItemService,
		elementItemService,
		userService,
		logger,
		$location,
		$routeParams) {
        logger = logger.forSource(controllerId);

        var isNew = $location.path() === '/manage/userElementItem/new';
        var isSaving = false;

        // Controller methods (alphabetically)
        var vm = this;
        vm.elementItemSet = [];
        vm.userSet = [];
        vm.cancelChanges = cancelChanges;
        vm.isSaveDisabled = isSaveDisabled;
        vm.userElementItem = null;
        vm.saveChanges = saveChanges;
        vm.hasChanges = hasChanges;

        initialize();

        /*** Implementations ***/

        function cancelChanges() {

            $location.path('/manage/userElementItem');

            if (userElementItemService.hasChanges()) {
                userElementItemService.rejectChanges();
                logWarning('Discarded pending change(s)', null, true);
            }
        }

        function hasChanges() {
            return userElementItemService.hasChanges();
        }

        function initialize() {

            elementItemService.getElementItemSet(false)
                .then(function (data) {
                    vm.elementItemSet = data;
                });

            userService.getUserSet(false)
                .then(function (data) {
                    vm.userSet = data;
                });

            if (isNew) {
                // TODO For development enviroment, create test entity?
            }
            else {
                userElementItemService.getUserElementItem($routeParams.Id)
                    .then(function (data) {
                        vm.userElementItem = data;
                    })
                    .catch(function (error) {
                        // TODO User-friendly message?
                    });
            }
        };

        function isSaveDisabled() {
            return isSaving ||
                (!isNew && !userElementItemService.hasChanges());
        }

        function saveChanges() {

            if (isNew) {
                userElementItemService.createUserElementItem(vm.userElementItem);
            } else {
                // To be able to do concurrency check, RowVersion field needs to be send to server
				// Since breeze only sends the modified fields, a fake modification had to be applied to RowVersion field
                var rowVersion = vm.userElementItem.RowVersion;
                vm.userElementItem.RowVersion = '';
                vm.userElementItem.RowVersion = rowVersion;
            }

            isSaving = true;
            userElementItemService.saveChanges()
                .then(function (result) {
                    $location.path('/manage/userElementItem');
                })
                .catch(function (error) {
                    // Conflict (Concurrency exception)
                    if (error.status === '409') {
                        // TODO Try to recover!
                    }
                })
                .finally(function () {
                    isSaving = false;
                });
        }
    };
})();
