//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userRoleEditController';
    angular.module('main')
        .controller(controllerId, ['userRoleService',
            'roleService',
            'userService',
            'logger',
            '$location',
            '$routeParams',
            userRoleEditController]);

    function userRoleEditController(userRoleService,
		roleService,
		userService,
		logger,
		$location,
		$routeParams) {
        logger = logger.forSource(controllerId);

        var isNew = $location.path() === '/manage/userRole/new';
        var isSaving = false;

        // Controller methods (alphabetically)
        var vm = this;
        vm.roleSet = [];
        vm.userSet = [];
        vm.cancelChanges = cancelChanges;
        vm.isSaveDisabled = isSaveDisabled;
        vm.entityErrors = [];
        vm.userRole = null;
        vm.saveChanges = saveChanges;
        vm.hasChanges = hasChanges;

        initialize();

        /*** Implementations ***/

        function cancelChanges() {

            $location.path('/manage/userRole');

            if (userRoleService.hasChanges()) {
                userRoleService.rejectChanges();
                logWarning('Discarded pending change(s)', null, true);
            }
        }

        function hasChanges() {
            return userRoleService.hasChanges();
        }

        function initialize() {

            roleService.getRoleSet(false)
                .then(function (data) {
                    vm.roleSet = data;
                });

            userService.getUserSet(false)
                .then(function (data) {
                    vm.userSet = data;
                });

            if (isNew) {
                // TODO For development enviroment, create test entity?
            }
            else {
                userRoleService.getUserRole($routeParams.Id)
                    .then(function (data) {
                        vm.userRole = data;
                    })
                    .catch(function (error) {
                        // TODO User-friendly message?
                    });
            }
        };

        function isSaveDisabled() {
            return isSaving ||
                (!isNew && !userRoleService.hasChanges());
        }

        function saveChanges() {

            if (isNew) {
                userRoleService.createUserRole(vm.userRole);
            } else {
                // To be able to do concurrency check, RowVersion field needs to be send to server
				// Since breeze only sends the modified fields, a fake modification had to be applied to RowVersion field
                var rowVersion = vm.userRole.RowVersion;
                vm.userRole.RowVersion = '';
                vm.userRole.RowVersion = rowVersion;
            }

            isSaving = true;
            userRoleService.saveChanges()
                .then(function (result) {
                    $location.path('/manage/userRole');
                })
                .catch(function (error) {
                    // Conflict (Concurrency exception)
                    if (error.status !== 'undefined' && error.status === '409') {
                        // TODO Try to recover!
                    } else if (error.entityErrors !== 'undefined') {
                        vm.entityErrors = error.entityErrors;
                    }
                })
                .finally(function () {
                    isSaving = false;
                });
        }
    };
})();
