//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    var controllerId = 'userResourcePoolIndexElementItemEditController';
    angular.module('main')
        .controller(controllerId, ['userResourcePoolIndexElementItemService',
            'elementItemService',
            'userResourcePoolIndexService',
            'logger',
            '$location',
            '$routeParams',
            userResourcePoolIndexElementItemEditController]);

    function userResourcePoolIndexElementItemEditController(userResourcePoolIndexElementItemService,
		elementItemService,
		userResourcePoolIndexService,
		logger,
		$location,
		$routeParams) {
        logger = logger.forSource(controllerId);

        var isNew = $location.path() === '/manage/userResourcePoolIndexElementItem/new';
        var isSaving = false;

        // Controller methods (alphabetically)
        var vm = this;
        vm.elementItemSet = [];
        vm.userResourcePoolIndexSet = [];
        vm.cancelChanges = cancelChanges;
        vm.isSaveDisabled = isSaveDisabled;
        vm.userResourcePoolIndexElementItem = null;
        vm.saveChanges = saveChanges;
        vm.hasChanges = hasChanges;

        initialize();

        /*** Implementations ***/

        function cancelChanges() {

            $location.path('/manage/userResourcePoolIndexElementItem');

            if (userResourcePoolIndexElementItemService.hasChanges()) {
                userResourcePoolIndexElementItemService.rejectChanges();
                logWarning('Discarded pending change(s)', null, true);
            }
        }

        function hasChanges() {
            return userResourcePoolIndexElementItemService.hasChanges();
        }

        function initialize() {

            elementItemService.getElementItemSet(false)
                .then(function (data) {
                    vm.elementItemSet = data;
                });

            userResourcePoolIndexService.getUserResourcePoolIndexSet(false)
                .then(function (data) {
                    vm.userResourcePoolIndexSet = data;
                });

            if (isNew) {
                // TODO For development enviroment, create test entity?
            }
            else {
                userResourcePoolIndexElementItemService.getUserResourcePoolIndexElementItem($routeParams.Id)
                    .then(function (data) {
                        vm.userResourcePoolIndexElementItem = data;
                    })
                    .catch(function (error) {
                        // TODO User-friendly message?
                    });
            }
        };

        function isSaveDisabled() {
            return isSaving ||
                (!isNew && !userResourcePoolIndexElementItemService.hasChanges());
        }

        function saveChanges() {

            if (isNew) {
                userResourcePoolIndexElementItemService.createUserResourcePoolIndexElementItem(vm.userResourcePoolIndexElementItem);
            } else {
                // To be able to do concurrency check, RowVersion field needs to be send to server
				// Since breeze only sends the modified fields, a fake modification had to be applied to RowVersion field
                var rowVersion = vm.userResourcePoolIndexElementItem.RowVersion;
                vm.userResourcePoolIndexElementItem.RowVersion = '';
                vm.userResourcePoolIndexElementItem.RowVersion = rowVersion;
            }

            isSaving = true;
            userResourcePoolIndexElementItemService.saveChanges()
                .then(function (result) {
                    $location.path('/manage/userResourcePoolIndexElementItem');
                })
                .catch(function (error) {
                    // Conflict (Concurrency exception)
                    if (error.status === '409') {
                        // TODO Try to recover!
                    }
                })
                .finally(function () {
                    isSaving = false;
                });
        }
    };
})();
