/*
EntityFramework.dll + EntityFramework.SqlServer.dll files under
C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE folder
were replaced with Entity Framework 6.1 versions.
v0.10.9
SH - 09 May '14
*/


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    document.write('\
	\
    <script src="/App/scripts/services/generated/elementService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/elementListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/elementEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/elementCellService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/elementCellListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/elementCellEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/elementFieldService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/elementFieldListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/elementFieldEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/elementItemService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/elementItemListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/elementItemEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/resourcePoolService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/resourcePoolListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/resourcePoolEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/resourcePoolIndexService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/resourcePoolIndexListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/resourcePoolIndexEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/roleService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/roleListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/roleEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/userService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/userListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/userEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/userClaimService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/userClaimListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/userClaimEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/userElementCellService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/userElementCellListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/userElementCellEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/userLoginService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/userLoginListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/userLoginEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/userResourcePoolService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/userResourcePoolListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/userResourcePoolEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/userResourcePoolIndexService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/userResourcePoolIndexListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/userResourcePoolIndexEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/userRoleService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/userRoleListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/userRoleEditController.js"></script>\
	\
\
');

})();
