/*
EntityFramework.dll + EntityFramework.SqlServer.dll files under
C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE folder
were replaced with Entity Framework 6.1 versions.
v0.10.9
SH - 09 May '14
*/


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

(function () {
    'use strict';

    document.write('\
	\
    <script src="/App/scripts/services/generated/elementService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/elementListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/elementEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/elementItemService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/elementItemListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/elementItemEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/organizationService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/organizationListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/organizationEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/organizationElementItemService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/organizationElementItemListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/organizationElementItemEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/resourcePoolService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/resourcePoolListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/resourcePoolEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/resourcePoolIndexService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/resourcePoolIndexListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/resourcePoolIndexEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/sectorService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/sectorListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/sectorEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/userService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/userListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/userEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/userElementItemService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/userElementItemListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/userElementItemEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/userOrganizationService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/userOrganizationListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/userOrganizationEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/userResourcePoolService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/userResourcePoolListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/userResourcePoolEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/userResourcePoolIndexService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/userResourcePoolIndexListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/userResourcePoolIndexEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/userResourcePoolIndexValueService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/userResourcePoolIndexValueListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/userResourcePoolIndexValueEditController.js"></script>\
	\
    <script src="/App/scripts/services/generated/userSectorRatingService.js"></script>\
    <script src="/App/scripts/controllers/manage/list/userSectorRatingListController.js"></script>\
    <script src="/App/scripts/controllers/manage/edit/userSectorRatingEditController.js"></script>\
	\
\
');

})();
